// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/antha-lang/antha/driver/antha_platereader_v1/platereader.proto

/*
Package antha_platereader_v1 is a generated protocol buffer package.

It is generated from these files:
	github.com/antha-lang/antha/driver/antha_platereader_v1/platereader.proto

It has these top-level messages:
	BoolReply
	ProtocolRunRequest
	Blank
*/
package antha_platereader_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BoolReply struct {
	Result bool `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *BoolReply) Reset()                    { *m = BoolReply{} }
func (m *BoolReply) String() string            { return proto.CompactTextString(m) }
func (*BoolReply) ProtoMessage()               {}
func (*BoolReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BoolReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type ProtocolRunRequest struct {
	ProtocolName string `protobuf:"bytes,1,opt,name=ProtocolName" json:"ProtocolName,omitempty"`
	PlateID      string `protobuf:"bytes,2,opt,name=PlateID" json:"PlateID,omitempty"`
}

func (m *ProtocolRunRequest) Reset()                    { *m = ProtocolRunRequest{} }
func (m *ProtocolRunRequest) String() string            { return proto.CompactTextString(m) }
func (*ProtocolRunRequest) ProtoMessage()               {}
func (*ProtocolRunRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtocolRunRequest) GetProtocolName() string {
	if m != nil {
		return m.ProtocolName
	}
	return ""
}

func (m *ProtocolRunRequest) GetPlateID() string {
	if m != nil {
		return m.PlateID
	}
	return ""
}

type Blank struct {
}

func (m *Blank) Reset()                    { *m = Blank{} }
func (m *Blank) String() string            { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()               {}
func (*Blank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*BoolReply)(nil), "antha.platereader.v1.BoolReply")
	proto.RegisterType((*ProtocolRunRequest)(nil), "antha.platereader.v1.ProtocolRunRequest")
	proto.RegisterType((*Blank)(nil), "antha.platereader.v1.Blank")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlateReader service

type PlateReaderClient interface {
	PRRunProtocolByName(ctx context.Context, in *ProtocolRunRequest, opts ...grpc.CallOption) (*BoolReply, error)
	PROpen(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error)
}

type plateReaderClient struct {
	cc *grpc.ClientConn
}

func NewPlateReaderClient(cc *grpc.ClientConn) PlateReaderClient {
	return &plateReaderClient{cc}
}

func (c *plateReaderClient) PRRunProtocolByName(ctx context.Context, in *ProtocolRunRequest, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.platereader.v1.PlateReader/PRRunProtocolByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plateReaderClient) PROpen(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*BoolReply, error) {
	out := new(BoolReply)
	err := grpc.Invoke(ctx, "/antha.platereader.v1.PlateReader/PROpen", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlateReader service

type PlateReaderServer interface {
	PRRunProtocolByName(context.Context, *ProtocolRunRequest) (*BoolReply, error)
	PROpen(context.Context, *Blank) (*BoolReply, error)
}

func RegisterPlateReaderServer(s *grpc.Server, srv PlateReaderServer) {
	s.RegisterService(&_PlateReader_serviceDesc, srv)
}

func _PlateReader_PRRunProtocolByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlateReaderServer).PRRunProtocolByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antha.platereader.v1.PlateReader/PRRunProtocolByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlateReaderServer).PRRunProtocolByName(ctx, req.(*ProtocolRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlateReader_PROpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlateReaderServer).PROpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antha.platereader.v1.PlateReader/PROpen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlateReaderServer).PROpen(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlateReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antha.platereader.v1.PlateReader",
	HandlerType: (*PlateReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PRRunProtocolByName",
			Handler:    _PlateReader_PRRunProtocolByName_Handler,
		},
		{
			MethodName: "PROpen",
			Handler:    _PlateReader_PROpen_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/antha-lang/antha/driver/antha_platereader_v1/platereader.proto",
}

func init() {
	proto.RegisterFile("github.com/antha-lang/antha/driver/antha_platereader_v1/platereader.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x09, 0x12, 0x29, 0x1d, 0x58, 0x0d, 0x08, 0x45, 0xb0, 0x00, 0x99, 0x4d, 0x37, 0x38,
	0x2a, 0xdc, 0x20, 0x62, 0x41, 0x37, 0x10, 0xcd, 0x05, 0x2a, 0xa7, 0x1d, 0xb5, 0x15, 0xae, 0x1d,
	0x5c, 0x3b, 0x52, 0xcf, 0xc6, 0xe5, 0x50, 0x5c, 0x82, 0x8a, 0x08, 0x52, 0x77, 0xfe, 0x7f, 0xbe,
	0xbf, 0x9f, 0x07, 0x26, 0x8b, 0x95, 0x5f, 0x86, 0x4a, 0xce, 0xec, 0x3a, 0x57, 0xc6, 0x2f, 0xd5,
	0x83, 0x56, 0x66, 0xb1, 0x3b, 0xe6, 0x73, 0xb7, 0x6a, 0xd8, 0xed, 0xc4, 0xb4, 0xd6, 0xca, 0xb3,
	0x63, 0x35, 0x67, 0x37, 0x6d, 0xc6, 0xf9, 0x9e, 0x94, 0xb5, 0xb3, 0xde, 0xe2, 0x65, 0xcc, 0xc9,
	0xfd, 0x41, 0x33, 0x16, 0xf7, 0x30, 0x2c, 0xac, 0xd5, 0xc4, 0xb5, 0xde, 0xe2, 0x15, 0xa4, 0x8e,
	0x37, 0x41, 0xfb, 0x2c, 0xb9, 0x4b, 0x46, 0xa7, 0xf4, 0xad, 0x04, 0x01, 0x96, 0x6d, 0xc7, 0xcc,
	0x6a, 0x0a, 0x86, 0xf8, 0x23, 0xf0, 0xc6, 0xa3, 0x80, 0xf3, 0xce, 0x7d, 0x55, 0x6b, 0x8e, 0x77,
	0x86, 0xf4, 0xcb, 0xc3, 0x0c, 0x06, 0x65, 0xfb, 0xe0, 0xe4, 0x39, 0x3b, 0x8e, 0xe3, 0x4e, 0x8a,
	0x01, 0x9c, 0x14, 0x5a, 0x99, 0xf7, 0xc7, 0xcf, 0x04, 0xce, 0xa2, 0x49, 0x11, 0x0a, 0x2b, 0xb8,
	0x28, 0x89, 0x82, 0xe9, 0x7a, 0x8a, 0x6d, 0x6c, 0x1a, 0xc9, 0x3e, 0x7e, 0xf9, 0x97, 0xeb, 0xfa,
	0xb6, 0x3f, 0xf9, 0xf3, 0x4d, 0x71, 0x84, 0x2f, 0x90, 0x96, 0xf4, 0x56, 0xb3, 0xc1, 0x9b, 0x7f,
	0xc2, 0x2d, 0xda, 0x01, 0x4d, 0x55, 0x1a, 0x97, 0xfb, 0xf4, 0x15, 0x00, 0x00, 0xff, 0xff, 0x7e,
	0x8c, 0x2e, 0xae, 0xa9, 0x01, 0x00, 0x00,
}
