steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://cloud-build-antha-images/read-github-netrc.enc', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=read-github-netrc.enc
  - --plaintext-file=.netrc
  - --location=global
  - --keyring=continuous-deployment
  - --key=read-github

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker build --force-rm -t 'eu.gcr.io/antha-images/antha-core:$COMMIT_SHA' --build-arg NETRC="$(cat .netrc)" .

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://cloud-build-antha-images/write-gitlab-antha-root-passwd.enc', '/docker-config/.']
  volumes:
  - name: 'docker'
    path: '/docker-config'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=/docker-config/write-gitlab-antha-root-passwd.enc
  - --plaintext-file=/docker-config/antha-root-passwd
  - --location=global
  - --keyring=continuous-deployment
  - --key=write-gitlab
  volumes:
  - name: 'docker'
    path: '/docker-config'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x -o nounset -o errexit -o pipefail
    cat /docker-config/antha-root-passwd | docker login -u antha-root --password-stdin repos.antha.com:5005
    REPOS="eu.gcr.io/antha-images/antha-core:$COMMIT_SHA eu.gcr.io/antha-images/antha-core:latest repos.antha.com:5005/antha-ninja/antha-core:latest repos.antha.com:5005/antha-ninja/antha-core:$COMMIT_SHA"
    for repo in $$REPOS; do
      docker tag eu.gcr.io/antha-images/antha-core:$COMMIT_SHA $repo
      docker push $repo
    done
  volumes:
  - name: 'docker'
    path: '/docker-config'
timeout: 1000s
options:
  machineType: 'N1_HIGHCPU_8'
