// Code generated by protoc-gen-go.
// source: github.com/antha-lang/antha/api/v1/inventory.proto
// DO NOT EDIT!

package org_antha_lang_antha_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type InventoryItem struct {
	// Inventory id
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Metadata
	Metadata map[string]*google_protobuf.Any `protobuf:"bytes,2,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Time this inventory item was created at
	CreatedAt *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	// History of this inventory item
	FromItems []*InventoryItem `protobuf:"bytes,4,rep,name=from_items,json=fromItems" json:"from_items,omitempty"`
	// Types that are valid to be assigned to Item:
	//	*InventoryItem_Tipbox
	//	*InventoryItem_Tipwaste
	//	*InventoryItem_Plate
	//	*InventoryItem_DeckPosition
	//	*InventoryItem_Component
	Item isInventoryItem_Item `protobuf_oneof:"item"`
}

func (m *InventoryItem) Reset()                    { *m = InventoryItem{} }
func (m *InventoryItem) String() string            { return proto.CompactTextString(m) }
func (*InventoryItem) ProtoMessage()               {}
func (*InventoryItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type isInventoryItem_Item interface {
	isInventoryItem_Item()
}

type InventoryItem_Tipbox struct {
	Tipbox *Tipbox `protobuf:"bytes,5,opt,name=tipbox,oneof"`
}
type InventoryItem_Tipwaste struct {
	Tipwaste *Tipwaste `protobuf:"bytes,6,opt,name=tipwaste,oneof"`
}
type InventoryItem_Plate struct {
	Plate *Plate `protobuf:"bytes,7,opt,name=plate,oneof"`
}
type InventoryItem_DeckPosition struct {
	DeckPosition *DeckPosition `protobuf:"bytes,8,opt,name=deck_position,json=deckPosition,oneof"`
}
type InventoryItem_Component struct {
	Component *Component `protobuf:"bytes,9,opt,name=component,oneof"`
}

func (*InventoryItem_Tipbox) isInventoryItem_Item()       {}
func (*InventoryItem_Tipwaste) isInventoryItem_Item()     {}
func (*InventoryItem_Plate) isInventoryItem_Item()        {}
func (*InventoryItem_DeckPosition) isInventoryItem_Item() {}
func (*InventoryItem_Component) isInventoryItem_Item()    {}

func (m *InventoryItem) GetItem() isInventoryItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *InventoryItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InventoryItem) GetMetadata() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *InventoryItem) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *InventoryItem) GetFromItems() []*InventoryItem {
	if m != nil {
		return m.FromItems
	}
	return nil
}

func (m *InventoryItem) GetTipbox() *Tipbox {
	if x, ok := m.GetItem().(*InventoryItem_Tipbox); ok {
		return x.Tipbox
	}
	return nil
}

func (m *InventoryItem) GetTipwaste() *Tipwaste {
	if x, ok := m.GetItem().(*InventoryItem_Tipwaste); ok {
		return x.Tipwaste
	}
	return nil
}

func (m *InventoryItem) GetPlate() *Plate {
	if x, ok := m.GetItem().(*InventoryItem_Plate); ok {
		return x.Plate
	}
	return nil
}

func (m *InventoryItem) GetDeckPosition() *DeckPosition {
	if x, ok := m.GetItem().(*InventoryItem_DeckPosition); ok {
		return x.DeckPosition
	}
	return nil
}

func (m *InventoryItem) GetComponent() *Component {
	if x, ok := m.GetItem().(*InventoryItem_Component); ok {
		return x.Component
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InventoryItem) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InventoryItem_OneofMarshaler, _InventoryItem_OneofUnmarshaler, _InventoryItem_OneofSizer, []interface{}{
		(*InventoryItem_Tipbox)(nil),
		(*InventoryItem_Tipwaste)(nil),
		(*InventoryItem_Plate)(nil),
		(*InventoryItem_DeckPosition)(nil),
		(*InventoryItem_Component)(nil),
	}
}

func _InventoryItem_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InventoryItem)
	// item
	switch x := m.Item.(type) {
	case *InventoryItem_Tipbox:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tipbox); err != nil {
			return err
		}
	case *InventoryItem_Tipwaste:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tipwaste); err != nil {
			return err
		}
	case *InventoryItem_Plate:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Plate); err != nil {
			return err
		}
	case *InventoryItem_DeckPosition:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeckPosition); err != nil {
			return err
		}
	case *InventoryItem_Component:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Component); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InventoryItem.Item has unexpected type %T", x)
	}
	return nil
}

func _InventoryItem_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InventoryItem)
	switch tag {
	case 5: // item.tipbox
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Tipbox)
		err := b.DecodeMessage(msg)
		m.Item = &InventoryItem_Tipbox{msg}
		return true, err
	case 6: // item.tipwaste
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Tipwaste)
		err := b.DecodeMessage(msg)
		m.Item = &InventoryItem_Tipwaste{msg}
		return true, err
	case 7: // item.plate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Plate)
		err := b.DecodeMessage(msg)
		m.Item = &InventoryItem_Plate{msg}
		return true, err
	case 8: // item.deck_position
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeckPosition)
		err := b.DecodeMessage(msg)
		m.Item = &InventoryItem_DeckPosition{msg}
		return true, err
	case 9: // item.component
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Component)
		err := b.DecodeMessage(msg)
		m.Item = &InventoryItem_Component{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InventoryItem_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InventoryItem)
	// item
	switch x := m.Item.(type) {
	case *InventoryItem_Tipbox:
		s := proto.Size(x.Tipbox)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InventoryItem_Tipwaste:
		s := proto.Size(x.Tipwaste)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InventoryItem_Plate:
		s := proto.Size(x.Plate)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InventoryItem_DeckPosition:
		s := proto.Size(x.DeckPosition)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InventoryItem_Component:
		s := proto.Size(x.Component)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Pipette tips in a box
type Tipbox struct {
	// Tipbox type
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *Tipbox) Reset()                    { *m = Tipbox{} }
func (m *Tipbox) String() string            { return proto.CompactTextString(m) }
func (*Tipbox) ProtoMessage()               {}
func (*Tipbox) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Tipbox) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Disposal for used pipette tips
type Tipwaste struct {
	// Tipwaste type
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *Tipwaste) Reset()                    { *m = Tipwaste{} }
func (m *Tipwaste) String() string            { return proto.CompactTextString(m) }
func (*Tipwaste) ProtoMessage()               {}
func (*Tipwaste) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Tipwaste) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Synthetic inventory item to represent position on deck
type DeckPosition struct {
	// Position
	Position string `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
}

func (m *DeckPosition) Reset()                    { *m = DeckPosition{} }
func (m *DeckPosition) String() string            { return proto.CompactTextString(m) }
func (*DeckPosition) ProtoMessage()               {}
func (*DeckPosition) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DeckPosition) GetPosition() string {
	if m != nil {
		return m.Position
	}
	return ""
}

// Plate
type Plate struct {
	// Plate type
	Type  string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Wells []*Well `protobuf:"bytes,2,rep,name=wells" json:"wells,omitempty"`
}

func (m *Plate) Reset()                    { *m = Plate{} }
func (m *Plate) String() string            { return proto.CompactTextString(m) }
func (*Plate) ProtoMessage()               {}
func (*Plate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Plate) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Plate) GetWells() []*Well {
	if m != nil {
		return m.Wells
	}
	return nil
}

// Well in plate
type Well struct {
	Position  *OrdinalCoord  `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Component *InventoryItem `protobuf:"bytes,2,opt,name=component" json:"component,omitempty"`
}

func (m *Well) Reset()                    { *m = Well{} }
func (m *Well) String() string            { return proto.CompactTextString(m) }
func (*Well) ProtoMessage()               {}
func (*Well) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Well) GetPosition() *OrdinalCoord {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Well) GetComponent() *InventoryItem {
	if m != nil {
		return m.Component
	}
	return nil
}

// Physical component, typically a liquid
type Component struct {
	// Component type
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	// Name
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Volume
	Volume *Measurement `protobuf:"bytes,3,opt,name=volume" json:"volume,omitempty"`
	// Viscosity
	Viscosity *Measurement `protobuf:"bytes,4,opt,name=viscosity" json:"viscosity,omitempty"`
	// Mass
	Mass *Measurement `protobuf:"bytes,5,opt,name=mass" json:"mass,omitempty"`
	// Amount (moles)
	Amount *Measurement `protobuf:"bytes,6,opt,name=amount" json:"amount,omitempty"`
	// If non-atomic component, this is what we are comprised of
	Components []*Component `protobuf:"bytes,7,rep,name=components" json:"components,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Component) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetVolume() *Measurement {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *Component) GetViscosity() *Measurement {
	if m != nil {
		return m.Viscosity
	}
	return nil
}

func (m *Component) GetMass() *Measurement {
	if m != nil {
		return m.Mass
	}
	return nil
}

func (m *Component) GetAmount() *Measurement {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Component) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func init() {
	proto.RegisterType((*InventoryItem)(nil), "org.antha_lang.antha.v1.InventoryItem")
	proto.RegisterType((*Tipbox)(nil), "org.antha_lang.antha.v1.Tipbox")
	proto.RegisterType((*Tipwaste)(nil), "org.antha_lang.antha.v1.Tipwaste")
	proto.RegisterType((*DeckPosition)(nil), "org.antha_lang.antha.v1.DeckPosition")
	proto.RegisterType((*Plate)(nil), "org.antha_lang.antha.v1.Plate")
	proto.RegisterType((*Well)(nil), "org.antha_lang.antha.v1.Well")
	proto.RegisterType((*Component)(nil), "org.antha_lang.antha.v1.Component")
}

func init() { proto.RegisterFile("github.com/antha-lang/antha/api/v1/inventory.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0x6f, 0x6b, 0xdb, 0x3e,
	0x10, 0xc7, 0x93, 0xd4, 0x49, 0xe3, 0x6b, 0xfb, 0xe3, 0x87, 0x18, 0xcc, 0x0b, 0x5b, 0xdb, 0x99,
	0x6d, 0x94, 0xc2, 0x1c, 0xfa, 0x87, 0xd1, 0x8e, 0xc1, 0xe8, 0x3f, 0x48, 0x61, 0x65, 0x99, 0x28,
	0xec, 0x61, 0x50, 0x6c, 0x35, 0x15, 0xb5, 0x24, 0x63, 0x2b, 0xe9, 0xf2, 0x2a, 0xf6, 0x64, 0x6f,
	0x74, 0xef, 0x60, 0x58, 0x52, 0x9c, 0xb4, 0x8b, 0x8b, 0xf7, 0xec, 0x84, 0xbf, 0x9f, 0xd3, 0xe9,
	0x7b, 0x77, 0x86, 0xfd, 0x11, 0x53, 0xb7, 0xe3, 0x61, 0x10, 0x4a, 0xde, 0x25, 0x42, 0xdd, 0x92,
	0xf7, 0x31, 0x11, 0x23, 0x13, 0x76, 0x49, 0xc2, 0xba, 0x93, 0xbd, 0x2e, 0x13, 0x13, 0x2a, 0x94,
	0x4c, 0xa7, 0x41, 0x92, 0x4a, 0x25, 0xd1, 0x73, 0x99, 0x8e, 0x02, 0xad, 0x18, 0xe4, 0x62, 0x13,
	0x06, 0x93, 0xbd, 0xce, 0x8b, 0x91, 0x94, 0xa3, 0x98, 0x76, 0xb5, 0x6c, 0x38, 0xbe, 0xe9, 0x12,
	0x61, 0x99, 0xce, 0xd6, 0xe3, 0x4f, 0x8a, 0x71, 0x9a, 0x29, 0xc2, 0x13, 0x2b, 0x08, 0x2a, 0x14,
	0x12, 0x4a, 0x99, 0x46, 0x56, 0x7f, 0x58, 0x41, 0xcf, 0x29, 0xc9, 0xc6, 0x29, 0xe5, 0x54, 0x28,
	0x43, 0xf9, 0xbf, 0x9a, 0xb0, 0x71, 0x39, 0x7b, 0xce, 0xa5, 0xa2, 0x1c, 0xfd, 0x07, 0x0d, 0x16,
	0x79, 0xf5, 0xed, 0xfa, 0x8e, 0x8b, 0x1b, 0x2c, 0x42, 0x7d, 0x68, 0x73, 0xaa, 0x48, 0x44, 0x14,
	0xf1, 0x1a, 0xdb, 0x2b, 0x3b, 0x6b, 0xfb, 0x87, 0x41, 0xc9, 0x7b, 0x83, 0x07, 0x99, 0x82, 0x2b,
	0x8b, 0x5d, 0x08, 0x95, 0x4e, 0x71, 0x91, 0x05, 0x1d, 0x03, 0x84, 0x29, 0x25, 0x8a, 0x46, 0x03,
	0xa2, 0xbc, 0x95, 0xed, 0xfa, 0xce, 0xda, 0x7e, 0x27, 0x30, 0x7e, 0x04, 0x33, 0x3f, 0x82, 0xeb,
	0x99, 0x1f, 0xd8, 0xb5, 0xea, 0x13, 0x85, 0x2e, 0x00, 0x6e, 0x52, 0xc9, 0x07, 0x4c, 0x51, 0x9e,
	0x79, 0x8e, 0x2e, 0xe7, 0x5d, 0xb5, 0x72, 0xb0, 0x9b, 0x93, 0x79, 0x94, 0xa1, 0x63, 0x68, 0x29,
	0x96, 0x0c, 0xe5, 0x0f, 0xaf, 0xa9, 0x6f, 0xdf, 0x2a, 0x4d, 0x71, 0xad, 0x65, 0xbd, 0x1a, 0xb6,
	0x00, 0xfa, 0x0c, 0x6d, 0xc5, 0x92, 0x7b, 0x92, 0x29, 0xea, 0xb5, 0x34, 0xfc, 0xfa, 0x29, 0x58,
	0x0b, 0x7b, 0x35, 0x5c, 0x40, 0xe8, 0x03, 0x34, 0x93, 0x98, 0x28, 0xea, 0xad, 0x6a, 0x7a, 0xb3,
	0x94, 0xee, 0xe7, 0xaa, 0x5e, 0x0d, 0x1b, 0x39, 0xfa, 0x02, 0x1b, 0x11, 0x0d, 0xef, 0x06, 0x89,
	0xcc, 0x98, 0x62, 0x52, 0x78, 0x6d, 0xcd, 0xbf, 0x2d, 0xe5, 0xcf, 0x69, 0x78, 0xd7, 0xb7, 0xe2,
	0x5e, 0x0d, 0xaf, 0x47, 0x0b, 0x67, 0x74, 0x0a, 0x6e, 0x28, 0x79, 0x22, 0x05, 0x15, 0xca, 0x73,
	0x75, 0x26, 0xbf, 0x34, 0xd3, 0xd9, 0x4c, 0xd9, 0xab, 0xe1, 0x39, 0xd6, 0xf9, 0x06, 0x1b, 0x0f,
	0x5a, 0x8c, 0xfe, 0x87, 0x95, 0x3b, 0x3a, 0xb5, 0xb3, 0x93, 0x87, 0x68, 0x17, 0x9a, 0x13, 0x12,
	0x8f, 0xa9, 0xd7, 0xd0, 0x57, 0x3c, 0xfb, 0xab, 0xcb, 0x27, 0x62, 0x8a, 0x8d, 0xe4, 0x63, 0xe3,
	0xa8, 0x7e, 0xda, 0x02, 0x27, 0x6f, 0xad, 0xff, 0x12, 0x5a, 0xc6, 0x79, 0x84, 0xc0, 0x51, 0xd3,
	0x84, 0xda, 0xa4, 0x3a, 0xf6, 0x37, 0xa1, 0x3d, 0xb3, 0x76, 0xe9, 0xf7, 0x5d, 0x58, 0x5f, 0x7c,
	0x3c, 0xea, 0x40, 0xbb, 0x70, 0xcd, 0xe8, 0x8a, 0xb3, 0xdf, 0x87, 0xa6, 0x36, 0x7a, 0x59, 0x22,
	0x74, 0x00, 0xcd, 0x7b, 0x1a, 0xc7, 0x99, 0x1d, 0xfc, 0x57, 0xa5, 0x0e, 0x7d, 0xa7, 0x71, 0x8c,
	0x8d, 0xd6, 0xff, 0x59, 0x07, 0x27, 0x3f, 0xa3, 0x93, 0x47, 0xd7, 0x3e, 0xd5, 0xac, 0xaf, 0x69,
	0xc4, 0x04, 0x89, 0xcf, 0xf2, 0x85, 0x9e, 0x57, 0x87, 0xce, 0x17, 0xdb, 0x64, 0x3c, 0xac, 0x3c,
	0xee, 0x05, 0xe8, 0xff, 0x6e, 0x80, 0x5b, 0xf4, 0x70, 0xe9, 0x43, 0x11, 0x38, 0x82, 0x70, 0xd3,
	0x26, 0x17, 0xeb, 0x18, 0x7d, 0x82, 0xd6, 0x44, 0xc6, 0x63, 0x4e, 0xed, 0x8a, 0xbe, 0x29, 0xbd,
	0xf8, 0x6a, 0xfe, 0x5b, 0xc1, 0x96, 0xc9, 0x07, 0x6c, 0xc2, 0xb2, 0x30, 0x7f, 0xc8, 0xd4, 0x73,
	0xfe, 0x21, 0xc1, 0x1c, 0x43, 0x47, 0xe0, 0x70, 0x92, 0x65, 0x76, 0x49, 0xab, 0xe1, 0x9a, 0xc8,
	0x6b, 0x27, 0x5c, 0x8e, 0x85, 0xb2, 0x3b, 0x5a, 0xb1, 0x76, 0xc3, 0xa0, 0x53, 0x80, 0xc2, 0xbc,
	0xcc, 0x5b, 0xd5, 0xbd, 0xaf, 0xb0, 0x1d, 0x78, 0x81, 0x1a, 0xb6, 0xf4, 0x88, 0x1f, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xf6, 0xbf, 0xdb, 0x50, 0x06, 0x00, 0x00,
}
