// antha/AnthaStandardLibrary/Packages/enzymes/_typeIIsassembly_test.go: Part of the Antha language
// Copyright (C) 2015 The Antha authors. All rights reserved.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
//
// For more information relating to the software or licensing issues please
// contact license@antha-lang.org or write to the Antha team c/o
// Synthace Ltd. The London Bioscience Innovation Centre
// 2 Royal College St, London NW1 0NH UK

package enzymes

import (
	"strings"
	"testing"
	"reflect"
	"github.com/antha-lang/antha/antha/anthalib/wtype"
)

var pSEVA651 = wtype.DNASequence{
	Nm:      "test Elektrified pSEVA651",
	Seq:     strings.ToUpper("ttaattaaagcggataacaatttcacacaggaggccgcctaggccgcggccgcgcgaattcgagctcggtacccggggatcctctagagtcgacctgcaggcatgcaagcttgcggccgcgtcgtgactgggaaaaccctggcgactagtcttggactcctgttgatagatccagtaatgacctcagaactccatctggatttgttcagaacgctcggttgccgccgggcgttttttattggtgagaatccaggggtccccaataattacgatttaaatttgacataagcctgttcggttcgtaaactgtaatgcaagtagcgtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttgtacagcctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaggtggctcaagtatgggcatcattcgcacatgtaggctcggccctgaccaagtcaaatccatgcgggctgctcttgatcttttcggtcgtgagttcggagacgtagccacctactcccaacatcagccggactccgattacctcgggaacttgctccgtagtaagacattcatcgcgcttgctgccttcgaccaagaagcggttgttggcgctctcgcggcttacgttctgcccaagtttgagcagccgcgtagtgagatctatatctatgatctcgcagtctccggagagcaccggaggcagggcattgccaccgcgctcatcaatctcctcaagcatgaggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtgatgcactttgatatcgacccaagtaccgccacctaacaattcgttcaagccgagatcggcttcccggccgcggagttgttcggtaaattggacaacggtccgcgcgttgtccttttccgctgcataaccctgcttcggggtcattatagcgattttttcggtatatccatcctttttcgcacgatatacaggattttgccaaagggttcgtgtagactttccttggtgtatccaacggcgtcagccgggcaggataggtgaagtaggcccacccgcgagcgggtgttccttcttcactgtcccttattcgcacctggcggtgctcaacgggaatcctgctctgcgaggctggccgtaggccggcctcagcctgccgccttgggccgggtgatgtcgtacttgcccgccgcgaactcggttaccgtccagcccagcgcgaccagctccggcaacgcctcgcgcacccgctggcggcgcttgcgcatggtcgaaccactggcctctgacggccagacatagccgcacaaggtatctatggaagccttgccggttttgccggggtcgatccagccacacagccgctggtgcagcaggcgggcggtttcgctgtccagcgcccgcacctcgtccatgctgatgcgcacatgctggccgccacccatgacggcctgcgcgatcaaggggttcagggccacgtacaggcgcccgtccgcctcgtcgctggcgtactccgacagcagccgaaacccctgccgcttgcggccattctgggcgatgatggataccttccaaaggcgctcgatgcagtcctgtatgtgcttgagcgccccaccactatcgacctctgccccgatttcctttgccagcgcccgatagctacctttgaccacatggcattcagcggtgacggcctcccacttgggttccaggaacagccggagctgccgtccgccttcggtcttgggttccgggccaagcactaggccattaggcccagccatggccaccagcccttgcaggatgcgcagatcatcagcgcccagcggctccgggccgctgaactcgatccgcttgccgtcgccgtagtcatacgtcacgtccagcttgctgcgcttgcgctcgccccgcttgagggcacggaacaggccgggggccagacagtgcgccgggtcgtgccggacgtggctgaggctgtgcttgttcttaggcttcaccacggggcacccccttgctcttgcgctgcctctccagcacggcgggcttgagcaccccgccgtcatgccgcctgaaccaccgatcagcgaacggtgcgccatagttggccttgctcacaccgaagcggacgaagaaccggcgctggtcgtcgtccacaccccattcctcggcctcggcgctggtcatgctcgacaggtaggactgccagcggatgttatcgaccagtaccgagctgccccggctggcctgctgctggtcgcctgcgcccatcatggccgcgcccttgctggcatggtgcaggaacacgatagagcacccggtatcggcggcgatggcctccatgcgaccgatgacctgggccatggggccgctggcgttttcttcctcgatgtggaaccggcgcagcgtgtccagcaccatcaggcggcggccctcggcggcgcgcttgaggccgtcgaaccactccggggccatgatgttgggcaggctgccgatcagcggctggatcagcaggccgtcagccacggcttgccgttcctcggcgctgaggtgcgccccaagggcgtgcaggcggtgatgaatggcggtgggcgggtcttcggcgggcaggtagatcaccgggccggtgggcagttcgcccacctccagcagatccggcccgcctgcaatctgtgcggccagttgcagggccagcatggatttaccggcaccaccgggcgacaccagcgccccgaccgtaccggccaccatgttgggcaaaacgtagtccagcggtggcggcgctgctgcgaacgcctccagaatattgataggcttatgggtagccattgattgcctcctttgcaggcagttggtggttaggcgctggcggggtcactacccccgccctgcgccgctctgagttcttccaggcactcgcgcagcgcctcgtattcgtcgtcggtcagccagaacttgcgctgacgcatccctttggccttcatgcgctcggcatatcgcgcttggcgtacagcgtcagggctggccagcaggtcgccggtctgcttgtccttttggtctttcatatcagtcaccgagaaacttgccggggccgaaaggcttgtcttcgcggaacaaggacaaggtgcagccgtcaaggttaaggctggccatatcagcgactgaaaagcggccagcctcggccttgtttgacgtataaccaaagccaccgggcaaccaatagcccttgtcacttttgatcaggtagaccgaccctgaagcgcttttttcgtattccataaaacccccttctgtgcgtgagtactcatagtataacaggcgtgagtaccaacgcaagcactacatgctgaaatctggcccgcccctgtccatgcctcgctggcggggtgccggtgcccgtgccagctcggcccgcgcaagctggacgctgggcagacccatgaccttgctgacggtgcgctcgatgtaatccgcttcgtggccgggcttgcgctctgccagcgctgggctggcctcggccatggccttgccgatttcctcggcactgcggccccggctggccagcttctgcgcggcgataaagtcgcacttgctgaggtcatcaccgaagcgcttgaccagcccggccatctcgctgcggtactcgtccagcgccgtgcgccggtggcggctaagctgccgctcgggcagttcgaggctggccagcctgcgggccttctcctgctgccgctgggcctgctcgatctgctggccagcctgctgcaccagcgccgggccagcggtggcggtcttgcccttggattcacgcagcagcacccacggctgataaccggcgcgggtggtgtgcttgtccttgcggttggtgaagcccgccaagcggccatagtggcggctgtcggcgctggccgggtcggcgtcgtactcgctggccagcgtccgggcaatctgcccccgaagttcaccgcctgcggcgtcggccaccttgacccatgcctgatagttcttcgggctggtttccactaccagggcaggctcccggccctcggctttcatgtcatccaggtcaaactcgctgaggtcgtccaccagcaccagaccatgccgctcctgctcggcgggcctgatatacacgtcattgccctgggcattcatccgcttgagccatggcgtgttctggagcacttcggcggctgaccattcccggttcatcatctggccggtggtggcgtccctgacgccgatatcgaagcgctcacagcccatggccttgagctgtcggcctatggcctgcaaagtcctgtcgttcttcatcgggccaccaagcgattcccacacattatacgagccggaagcataaagtgtaaagcctagatccgaaggatgagccgggctgaatgatcgaccgagacaggccctgcggggctgcacacgcgcccccacccttcgggtagggggaaaggccgctaaagcggctaaaagcgctccagcgtatttctgcggggtttggtgtggggtttagcgggctttgcccgcctttccccctgccgcgcagcggtggggcggtgtgtagcctagcgcagcgaatagaccagctatccggcctctggccgggcatattgggcaagggcagcagcgccccacaagggcgctgataaccgcgcctagtggattattcttagataatcatggatggatttttccaacaccccgccagcccccgcccctgctgggtttgcaggtttgggggcgtgacagttattgcaggggttcgtgacagttattgcaggggggcgtgacagttattgcaggggttcgtgacagttagggcgcgcccagctgtctagggcggcggatttgtcctactcaggagagcgttcaccgacaaacaacagataaaacgaaaggcccagtctttcgactgagcctttcgttttatttgatgcctGCTCTTCTATGatatatatatataGGTAGAAGAGC"),
	Plasmid: true,
}
var comet1part = wtype.DNASequence{
	Nm:      "test comet 1 part",
	Seq:     strings.ToUpper("gctcttctatgacggcattgacggaaggcgcaaaattgttcgaaaaagaaatcccatacatcaccgaactggaaggcgatgttgaaggtatgaagttcatcattaagggtgagggcaccggcgatgcaactacgggcaccattaaagcgaagtatatctgcaccaccggtgacgttccggtgccgtggagcacgctggtcaccaccctgacctatggcgcgcagtgtttcgcgaagtacggtccggaactgaaggacttctataagagctgtatgcctgagggctatgttcaggagcgtaccattacctttgagggtgatggtgtctttaagacgcgtgctgaggtgacctttgagaatggttccgtgtacaatcgcgtgaaactgaatggtcaaggttttaagaaagatggtcacgtgctgggcaaaaacctggagtttaactttactccgcattgcctgtgcatttggggcgaccaagcgaaccacggtctgaaaagcgcgttcaagattatgcacgagattacgggtagcaaagaggacttcatcgtggccgaccacacgcagatgaacaccccgatcggtggcggtccggtccatgtcccggagtaccaccacttgaccgtttggacctctttcggtaaagacccggatgatgacgaaacggatcatctgaatattgttgaggttatcaaagccgtcgacctggaaacttaccgttaatgataatgaggtagaagagc"),
	Plasmid: false,
}
var cometfwdsapI = wtype.DNASequence{
	Nm:      "test comet fwd sapI",
	Seq:     strings.ToUpper("tatgacggcattgacggaaggcgcaaaattgttcgaaaaagaaatcccatacatcaccgaactggaaggcgatgttgaaggtatgaagttcatcattaagggtgagggcaccggcgatgcaactacgggcaccattaaagcgaagtatatctgcaccaccggtgacgttccggtgccgtggagcacgctggtcaccaccctgacctatggcgcgcagtgtttcgcgaagtacggtccggaactgaaggacttctataagagctgtatgcctgagggctatgttcaggagcgtaccattacctttgagggtgatggtgtctttaagacgcgtgctgaggtgacctttgagaatggttccgtgtacaatcgcgtgaaactgaatggtcaaggttttaagaaagatggtcacgtgctgggcaaaaacctggagtttaactttactccgcattgcctgtgcatttggggcgaccaagcgaaccacggtctgaaaagcgcgttcaagattatgcacgagattacgggtagcaaagaggacttcatcgtggccgaccacacgcagatgaacaccccgatcggtggcggtccggtccatgtcccggagtaccaccacttgaccgtttggacctctttcggtaaagacccggatgatgacgaaacggatcatctgaatattgttgaggttatcaaagccgtcgacctggaaacttaccgttaatgataatgaggtagaagagc"),
	Plasmid: false,
}
var comet2part1 = wtype.DNASequence{
	Nm:      "test comet 2.1 part",
	Seq:     strings.ToUpper("gctcttctatgacggcattgacggaaggcgcaaaattgttcgaaaaagaaatcccatacatcaccgaactggaaggcgatgttgaaggtatgaagttcatcattaagggtgagggcaccggcgatgcaactacgggcaccattaaagcgaagtatatctgcaccaccggtgacgttccggtgccgtggagcacgctggtcaccaccctgacctatggcgcgcagtgtttcgcgaagtacggtccggaactggaagagc"),
	Plasmid: false,
}
var comet2part2 = wtype.DNASequence{
	Nm:      "test comet 2.2 part",
	Seq:     strings.ToUpper("gctcttcgactgaaggacttctataagagctgtatgcctgagggctatgttcaggagcgtaccattacctttgagggtgatggtgtctttaagacgcgtgctgaggtgacctttgagaatggttccgtgtacaatcgcgtgaaactgaatggtcaaggttttaagaaagatggtcacgtgctgggcaaaaacctggagtttaactttactccgcattgcctgtgcatttggggcgaccaagcgaaccacggtctgaaaagcgcgttcaagattatgcacgagattacgggtagcaaagaggacttcatcgtggccgaccacacgcagatgaacaccccgatcggtggcggtccggtccatgtcccggagtaccaccacttgaccgtttggacctctttcggtaaagacccggatgatgacgaaacggatcatctgaatattgttgaggttatcaaagccgtcgacctggaaacttaccgttaatgataatgaggtagaagagc"),
	Plasmid: false,
}

type restrictionsitetest struct {
	sequence   wtype.DNASequence
	enzymelist []wtype.RestrictionEnzyme
	sitesfound []RestrictionSites
}

var restrictionsitetests = []restrictionsitetest{
	{pSEVA651,
		[]wtype.RestrictionEnzyme{SapI.RestrictionEnzyme, BsaI.RestrictionEnzyme},
		[]RestrictionSites{
			{
				SapI.RestrictionEnzyme,
				"GCTCTTC",
				true,
				2,
				[]int{5154},
				[]int{5182},
			},
			{
				BsaI.RestrictionEnzyme,
				"GGTCTC",
				false,
				0,
				[]int{},
				[]int{},
			},
		},
	},
}

func TestRestrictionsitefinder(t *testing.T) {
	for _, test := range restrictionsitetests {
		sitesFound := Restrictionsitefinder(test.sequence, test.enzymelist)
		for i := 0; i < len(sitesFound); i++ {
			if sitesFound[i].Numberofsites != test.sitesfound[i].Numberofsites {
				t.Error(
					"For", test.sequence.Name(), "\n",
					"and", test.enzymelist[i].Name(), "\n",
					"expected", test.sitesfound[i].Numberofsites, "sites \n",
					"got", sitesFound[i].Numberofsites, "sites \n",
				)
			}
			for j := range sitesFound[i].Forwardpositions {
				if j == len(test.sitesfound[i].Forwardpositions){
					t.Error(
						"For", test.sequence.Name(), "\n",
						"and", test.enzymelist[i].Name(), "\n",
						"expected", test.sitesfound[i].Forwardpositions, "\n",
						"got", sitesFound[i].Forwardpositions, "\n",
					)
					break
				}else if sitesFound[i].Forwardpositions[j] != test.sitesfound[i].Forwardpositions[j] {
					t.Error(
						"For", test.sequence.Name(), "\n",
						"and", test.enzymelist[i].Name(), "\n",
						"expected", test.sitesfound[i].Forwardpositions, "\n",
						"got", sitesFound[i].Forwardpositions, "\n",
					)
				}
			}
			for j := range sitesFound[i].Reversepositions {
				if j == len(test.sitesfound[i].Reversepositions){
					t.Error(
						"For", test.sequence.Name(), "\n",
						"and", test.enzymelist[i].Name(), "\n",
						"expected", test.sitesfound[i].Reversepositions, "\n",
						"got", sitesFound[i].Reversepositions, "\n",
					)
					break
				}else if sitesFound[i].Reversepositions[j] != test.sitesfound[i].Reversepositions[j] {
					// fmt.Println("\x1b[31;1m", r, "\x1b[0m", "\n")
					t.Error(
						"For", test.sequence.Name(), "\n",
						"and", test.enzymelist[i].Name(), "\n",
						"expected", test.sitesfound[i].Reversepositions, "\n",
						"got", sitesFound[i].Reversepositions, "\n",
					)
				}
			}
		}
	}
}

// new test type
type digesttest struct {
	sequence          wtype.DNASequence
	enzyme            wtype.RestrictionEnzyme
	doublestranded    []wtype.DNASequence
	Finalfragments    []string
	Stickyends_5prime []string
	Stickyends_3prime []string
}

// create an array of these tests (array of 1 currently)
var digesttests = []digesttest{
	digesttest{
		sequence:          pSEVA651,
		enzyme:            SapI.RestrictionEnzyme,
		doublestranded:    []wtype.DNASequence{
		{Nm: "Fwdsequence", 
		Seq: strings.ToUpper("ttaattaaagcggataacaatttcacacaggaggccgcctaggccgcggccgcgcgaattcgagctcggtacccggggatcctctagagtcgacctgcaggcatgcaagcttgcggccgcgtcgtgactgggaaaaccctggcgactagtcttggactcctgttgatagatccagtaatgacctcagaactccatctggatttgttcagaacgctcggttgccgccgggcgttttttattggtgagaatccaggggtccccaataattacgatttaaatttgacataagcctgttcggttcgtaaactgtaatgcaagtagcgtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttgtacagcctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaggtggctcaagtatgggcatcattcgcacatgtaggctcggccctgaccaagtcaaatccatgcgggctgctcttgatcttttcggtcgtgagttcggagacgtagccacctactcccaacatcagccggactccgattacctcgggaacttgctccgtagtaagacattcatcgcgcttgctgccttcgaccaagaagcggttgttggcgctctcgcggcttacgttctgcccaagtttgagcagccgcgtagtgagatctatatctatgatctcgcagtctccggagagcaccggaggcagggcattgccaccgcgctcatcaatctcctcaagcatgaggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtgatgcactttgatatcgacccaagtaccgccacctaacaattcgttcaagccgagatcggcttcccggccgcggagttgttcggtaaattggacaacggtccgcgcgttgtccttttccgctgcataaccctgcttcggggtcattatagcgattttttcggtatatccatcctttttcgcacgatatacaggattttgccaaagggttcgtgtagactttccttggtgtatccaacggcgtcagccgggcaggataggtgaagtaggcccacccgcgagcgggtgttccttcttcactgtcccttattcgcacctggcggtgctcaacgggaatcctgctctgcgaggctggccgtaggccggcctcagcctgccgccttgggccgggtgatgtcgtacttgcccgccgcgaactcggttaccgtccagcccagcgcgaccagctccggcaacgcctcgcgcacccgctggcggcgcttgcgcatggtcgaaccactggcctctgacggccagacatagccgcacaaggtatctatggaagccttgccggttttgccggggtcgatccagccacacagccgctggtgcagcaggcgggcggtttcgctgtccagcgcccgcacctcgtccatgctgatgcgcacatgctggccgccacccatgacggcctgcgcgatcaaggggttcagggccacgtacaggcgcccgtccgcctcgtcgctggcgtactccgacagcagccgaaacccctgccgcttgcggccattctgggcgatgatggataccttccaaaggcgctcgatgcagtcctgtatgtgcttgagcgccccaccactatcgacctctgccccgatttcctttgccagcgcccgatagctacctttgaccacatggcattcagcggtgacggcctcccacttgggttccaggaacagccggagctgccgtccgccttcggtcttgggttccgggccaagcactaggccattaggcccagccatggccaccagcccttgcaggatgcgcagatcatcagcgcccagcggctccgggccgctgaactcgatccgcttgccgtcgccgtagtcatacgtcacgtccagcttgctgcgcttgcgctcgccccgcttgagggcacggaacaggccgggggccagacagtgcgccgggtcgtgccggacgtggctgaggctgtgcttgttcttaggcttcaccacggggcacccccttgctcttgcgctgcctctccagcacggcgggcttgagcaccccgccgtcatgccgcctgaaccaccgatcagcgaacggtgcgccatagttggccttgctcacaccgaagcggacgaagaaccggcgctggtcgtcgtccacaccccattcctcggcctcggcgctggtcatgctcgacaggtaggactgccagcggatgttatcgaccagtaccgagctgccccggctggcctgctgctggtcgcctgcgcccatcatggccgcgcccttgctggcatggtgcaggaacacgatagagcacccggtatcggcggcgatggcctccatgcgaccgatgacctgggccatggggccgctggcgttttcttcctcgatgtggaaccggcgcagcgtgtccagcaccatcaggcggcggccctcggcggcgcgcttgaggccgtcgaaccactccggggccatgatgttgggcaggctgccgatcagcggctggatcagcaggccgtcagccacggcttgccgttcctcggcgctgaggtgcgccccaagggcgtgcaggcggtgatgaatggcggtgggcgggtcttcggcgggcaggtagatcaccgggccggtgggcagttcgcccacctccagcagatccggcccgcctgcaatctgtgcggccagttgcagggccagcatggatttaccggcaccaccgggcgacaccagcgccccgaccgtaccggccaccatgttgggcaaaacgtagtccagcggtggcggcgctgctgcgaacgcctccagaatattgataggcttatgggtagccattgattgcctcctttgcaggcagttggtggttaggcgctggcggggtcactacccccgccctgcgccgctctgagttcttccaggcactcgcgcagcgcctcgtattcgtcgtcggtcagccagaacttgcgctgacgcatccctttggccttcatgcgctcggcatatcgcgcttggcgtacagcgtcagggctggccagcaggtcgccggtctgcttgtccttttggtctttcatatcagtcaccgagaaacttgccggggccgaaaggcttgtcttcgcggaacaaggacaaggtgcagccgtcaaggttaaggctggccatatcagcgactgaaaagcggccagcctcggccttgtttgacgtataaccaaagccaccgggcaaccaatagcccttgtcacttttgatcaggtagaccgaccctgaagcgcttttttcgtattccataaaacccccttctgtgcgtgagtactcatagtataacaggcgtgagtaccaacgcaagcactacatgctgaaatctggcccgcccctgtccatgcctcgctggcggggtgccggtgcccgtgccagctcggcccgcgcaagctggacgctgggcagacccatgaccttgctgacggtgcgctcgatgtaatccgcttcgtggccgggcttgcgctctgccagcgctgggctggcctcggccatggccttgccgatttcctcggcactgcggccccggctggccagcttctgcgcggcgataaagtcgcacttgctgaggtcatcaccgaagcgcttgaccagcccggccatctcgctgcggtactcgtccagcgccgtgcgccggtggcggctaagctgccgctcgggcagttcgaggctggccagcctgcgggccttctcctgctgccgctgggcctgctcgatctgctggccagcctgctgcaccagcgccgggccagcggtggcggtcttgcccttggattcacgcagcagcacccacggctgataaccggcgcgggtggtgtgcttgtccttgcggttggtgaagcccgccaagcggccatagtggcggctgtcggcgctggccgggtcggcgtcgtactcgctggccagcgtccgggcaatctgcccccgaagttcaccgcctgcggcgtcggccaccttgacccatgcctgatagttcttcgggctggtttccactaccagggcaggctcccggccctcggctttcatgtcatccaggtcaaactcgctgaggtcgtccaccagcaccagaccatgccgctcctgctcggcgggcctgatatacacgtcattgccctgggcattcatccgcttgagccatggcgtgttctggagcacttcggcggctgaccattcccggttcatcatctggccggtggtggcgtccctgacgccgatatcgaagcgctcacagcccatggccttgagctgtcggcctatggcctgcaaagtcctgtcgttcttcatcgggccaccaagcgattcccacacattatacgagccggaagcataaagtgtaaagcctagatccgaaggatgagccgggctgaatgatcgaccgagacaggccctgcggggctgcacacgcgcccccacccttcgggtagggggaaaggccgctaaagcggctaaaagcgctccagcgtatttctgcggggtttggtgtggggtttagcgggctttgcccgcctttccccctgccgcgcagcggtggggcggtgtgtagcctagcgcagcgaatagaccagctatccggcctctggccgggcatattgggcaagggcagcagcgccccacaagggcgctgataaccgcgcctagtggattattcttagataatcatggatggatttttccaacaccccgccagcccccgcccctgctgggtttgcaggtttgggggcgtgacagttattgcaggggttcgtgacagttattgcaggggggcgtgacagttattgcaggggttcgtgacagttagggcgcgcccagctgtctagggcggcggatttgtcctactcaggagagcgttcaccgacaaacaacagataaaacgaaaggcccagtctttcgactgagcctttcgttttatttgatgcctGCTCTTCTATGatatatatatataGGTAGAAGAGC"),
		Plasmid: true}, 
		{Nm: "Reversecomplement", 
		Seq: strings.ToUpper("GCTCTTCTACCtatatatatatatCATAGAAGAGCaggcatcaaataaaacgaaaggctcagtcgaaagactgggcctttcgttttatctgttgtttgtcggtgaacgctctcctgagtaggacaaatccgccgccctagacagctgggcgcgccctaactgtcacgaacccctgcaataactgtcacgcccccctgcaataactgtcacgaacccctgcaataactgtcacgcccccaaacctgcaaacccagcaggggcgggggctggcggggtgttggaaaaatccatccatgattatctaagaataatccactaggcgcggttatcagcgcccttgtggggcgctgctgcccttgcccaatatgcccggccagaggccggatagctggtctattcgctgcgctaggctacacaccgccccaccgctgcgcggcagggggaaaggcgggcaaagcccgctaaaccccacaccaaaccccgcagaaatacgctggagcgcttttagccgctttagcggcctttccccctacccgaagggtgggggcgcgtgtgcagccccgcagggcctgtctcggtcgatcattcagcccggctcatccttcggatctaggctttacactttatgcttccggctcgtataatgtgtgggaatcgcttggtggcccgatgaagaacgacaggactttgcaggccataggccgacagctcaaggccatgggctgtgagcgcttcgatatcggcgtcagggacgccaccaccggccagatgatgaaccgggaatggtcagccgccgaagtgctccagaacacgccatggctcaagcggatgaatgcccagggcaatgacgtgtatatcaggcccgccgagcaggagcggcatggtctggtgctggtggacgacctcagcgagtttgacctggatgacatgaaagccgagggccgggagcctgccctggtagtggaaaccagcccgaagaactatcaggcatgggtcaaggtggccgacgccgcaggcggtgaacttcgggggcagattgcccggacgctggccagcgagtacgacgccgacccggccagcgccgacagccgccactatggccgcttggcgggcttcaccaaccgcaaggacaagcacaccacccgcgccggttatcagccgtgggtgctgctgcgtgaatccaagggcaagaccgccaccgctggcccggcgctggtgcagcaggctggccagcagatcgagcaggcccagcggcagcaggagaaggcccgcaggctggccagcctcgaactgcccgagcggcagcttagccgccaccggcgcacggcgctggacgagtaccgcagcgagatggccgggctggtcaagcgcttcggtgatgacctcagcaagtgcgactttatcgccgcgcagaagctggccagccggggccgcagtgccgaggaaatcggcaaggccatggccgaggccagcccagcgctggcagagcgcaagcccggccacgaagcggattacatcgagcgcaccgtcagcaaggtcatgggtctgcccagcgtccagcttgcgcgggccgagctggcacgggcaccggcaccccgccagcgaggcatggacaggggcgggccagatttcagcatgtagtgcttgcgttggtactcacgcctgttatactatgagtactcacgcacagaagggggttttatggaatacgaaaaaagcgcttcagggtcggtctacctgatcaaaagtgacaagggctattggttgcccggtggctttggttatacgtcaaacaaggccgaggctggccgcttttcagtcgctgatatggccagccttaaccttgacggctgcaccttgtccttgttccgcgaagacaagcctttcggccccggcaagtttctcggtgactgatatgaaagaccaaaaggacaagcagaccggcgacctgctggccagccctgacgctgtacgccaagcgcgatatgccgagcgcatgaaggccaaagggatgcgtcagcgcaagttctggctgaccgacgacgaatacgaggcgctgcgcgagtgcctggaagaactcagagcggcgcagggcgggggtagtgaccccgccagcgcctaaccaccaactgcctgcaaaggaggcaatcaatggctacccataagcctatcaatattctggaggcgttcgcagcagcgccgccaccgctggactacgttttgcccaacatggtggccggtacggtcggggcgctggtgtcgcccggtggtgccggtaaatccatgctggccctgcaactggccgcacagattgcaggcgggccggatctgctggaggtgggcgaactgcccaccggcccggtgatctacctgcccgccgaagacccgcccaccgccattcatcaccgcctgcacgcccttggggcgcacctcagcgccgaggaacggcaagccgtggctgacggcctgctgatccagccgctgatcggcagcctgcccaacatcatggccccggagtggttcgacggcctcaagcgcgccgccgagggccgccgcctgatggtgctggacacgctgcgccggttccacatcgaggaagaaaacgccagcggccccatggcccaggtcatcggtcgcatggaggccatcgccgccgataccgggtgctctatcgtgttcctgcaccatgccagcaagggcgcggccatgatgggcgcaggcgaccagcagcaggccagccggggcagctcggtactggtcgataacatccgctggcagtcctacctgtcgagcatgaccagcgccgaggccgaggaatggggtgtggacgacgaccagcgccggttcttcgtccgcttcggtgtgagcaaggccaactatggcgcaccgttcgctgatcggtggttcaggcggcatgacggcggggtgctcaagcccgccgtgctggagaggcagcgcaagagcaagggggtgccccgtggtgaagcctaagaacaagcacagcctcagccacgtccggcacgacccggcgcactgtctggcccccggcctgttccgtgccctcaagcggggcgagcgcaagcgcagcaagctggacgtgacgtatgactacggcgacggcaagcggatcgagttcagcggcccggagccgctgggcgctgatgatctgcgcatcctgcaagggctggtggccatggctgggcctaatggcctagtgcttggcccggaacccaagaccgaaggcggacggcagctccggctgttcctggaacccaagtgggaggccgtcaccgctgaatgccatgtggtcaaaggtagctatcgggcgctggcaaaggaaatcggggcagaggtcgatagtggtggggcgctcaagcacatacaggactgcatcgagcgcctttggaaggtatccatcatcgcccagaatggccgcaagcggcaggggtttcggctgctgtcggagtacgccagcgacgaggcggacgggcgcctgtacgtggccctgaaccccttgatcgcgcaggccgtcatgggtggcggccagcatgtgcgcatcagcatggacgaggtgcgggcgctggacagcgaaaccgcccgcctgctgcaccagcggctgtgtggctggatcgaccccggcaaaaccggcaaggcttccatagataccttgtgcggctatgtctggccgtcagaggccagtggttcgaccatgcgcaagcgccgccagcgggtgcgcgaggcgttgccggagctggtcgcgctgggctggacggtaaccgagttcgcggcgggcaagtacgacatcacccggcccaaggcggcaggctgaggccggcctacggccagcctcgcagagcaggattcccgttgagcaccgccaggtgcgaataagggacagtgaagaaggaacacccgctcgcgggtgggcctacttcacctatcctgcccggctgacgccgttggatacaccaaggaaagtctacacgaaccctttggcaaaatcctgtatatcgtgcgaaaaaggatggatataccgaaaaaatcgctataatgaccccgaagcagggttatgcagcggaaaaggacaacgcgcggaccgttgtccaatttaccgaacaactccgcggccgggaagccgatctcggcttgaacgaattgttaggtggcggtacttgggtcgatatcaaagtgcatcacttcttcccgtatgcccaactttgtatagagagccactgcgggatcgtcaccgtaatctgcttgcacgtagatcacataagcaccaagcgcgttggcctcatgcttgaggagattgatgagcgcggtggcaatgccctgcctccggtgctctccggagactgcgagatcatagatatagatctcactacgcggctgctcaaacttgggcagaacgtaagccgcgagagcgccaacaaccgcttcttggtcgaaggcagcaagcgcgatgaatgtcttactacggagcaagttcccgaggtaatcggagtccggctgatgttgggagtaggtggctacgtctccgaactcacgaccgaaaagatcaagagcagcccgcatggatttgacttggtcagggccgagcctacatgtgcgaatgatgcccatacttgagccacctaactttgttttagggcgactgccctgctgcgtaacatcgttgctgctgcgtaacatcgttgctgctccataacatcaaacatcgacccacggcgtaacgcgcttgctgcttggatgcccgaggcataggctgtacaaaaaaacagtcataacaagccatgaaaaccgccactgcgccgttaccaccgctgcgttcggtcaaggttctggaccagttgcgtgagcgcatacgctacttgcattacagtttacgaaccgaacaggcttatgtcaaatttaaatcgtaattattggggacccctggattctcaccaataaaaaacgcccggcggcaaccgagcgttctgaacaaatccagatggagttctgaggtcattactggatctatcaacaggagtccaagactagtcgccagggttttcccagtcacgacgcggccgcaagcttgcatgcctgcaggtcgactctagaggatccccgggtaccgagctcgaattcgcgcggccgcggcctaggcggcctcctgtgtgaaattgttatccgctttaattaa"),
		Plasmid: true},
		},
		Finalfragments:    []string{strings.ToUpper("GGTAGAAGAGCttaattaaagcggataacaatttcacacaggaggccgcctaggccgcggccgcgcgaattcgagctcggtacccggggatcctctagagtcgacctgcaggcatgcaagcttgcggccgcgtcgtgactgggaaaaccctggcgactagtcttggactcctgttgatagatccagtaatgacctcagaactccatctggatttgttcagaacgctcggttgccgccgggcgttttttattggtgagaatccaggggtccccaataattacgatttaaatttgacataagcctgttcggttcgtaaactgtaatgcaagtagcgtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttgtacagcctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaggtggctcaagtatgggcatcattcgcacatgtaggctcggccctgaccaagtcaaatccatgcgggctgctcttgatcttttcggtcgtgagttcggagacgtagccacctactcccaacatcagccggactccgattacctcgggaacttgctccgtagtaagacattcatcgcgcttgctgccttcgaccaagaagcggttgttggcgctctcgcggcttacgttctgcccaagtttgagcagccgcgtagtgagatctatatctatgatctcgcagtctccggagagcaccggaggcagggcattgccaccgcgctcatcaatctcctcaagcatgaggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtgatgcactttgatatcgacccaagtaccgccacctaacaattcgttcaagccgagatcggcttcccggccgcggagttgttcggtaaattggacaacggtccgcgcgttgtccttttccgctgcataaccctgcttcggggtcattatagcgattttttcggtatatccatcctttttcgcacgatatacaggattttgccaaagggttcgtgtagactttccttggtgtatccaacggcgtcagccgggcaggataggtgaagtaggcccacccgcgagcgggtgttccttcttcactgtcccttattcgcacctggcggtgctcaacgggaatcctgctctgcgaggctggccgtaggccggcctcagcctgccgccttgggccgggtgatgtcgtacttgcccgccgcgaactcggttaccgtccagcccagcgcgaccagctccggcaacgcctcgcgcacccgctggcggcgcttgcgcatggtcgaaccactggcctctgacggccagacatagccgcacaaggtatctatggaagccttgccggttttgccggggtcgatccagccacacagccgctggtgcagcaggcgggcggtttcgctgtccagcgcccgcacctcgtccatgctgatgcgcacatgctggccgccacccatgacggcctgcgcgatcaaggggttcagggccacgtacaggcgcccgtccgcctcgtcgctggcgtactccgacagcagccgaaacccctgccgcttgcggccattctgggcgatgatggataccttccaaaggcgctcgatgcagtcctgtatgtgcttgagcgccccaccactatcgacctctgccccgatttcctttgccagcgcccgatagctacctttgaccacatggcattcagcggtgacggcctcccacttgggttccaggaacagccggagctgccgtccgccttcggtcttgggttccgggccaagcactaggccattaggcccagccatggccaccagcccttgcaggatgcgcagatcatcagcgcccagcggctccgggccgctgaactcgatccgcttgccgtcgccgtagtcatacgtcacgtccagcttgctgcgcttgcgctcgccccgcttgagggcacggaacaggccgggggccagacagtgcgccgggtcgtgccggacgtggctgaggctgtgcttgttcttaggcttcaccacggggcacccccttgctcttgcgctgcctctccagcacggcgggcttgagcaccccgccgtcatgccgcctgaaccaccgatcagcgaacggtgcgccatagttggccttgctcacaccgaagcggacgaagaaccggcgctggtcgtcgtccacaccccattcctcggcctcggcgctggtcatgctcgacaggtaggactgccagcggatgttatcgaccagtaccgagctgccccggctggcctgctgctggtcgcctgcgcccatcatggccgcgcccttgctggcatggtgcaggaacacgatagagcacccggtatcggcggcgatggcctccatgcgaccgatgacctgggccatggggccgctggcgttttcttcctcgatgtggaaccggcgcagcgtgtccagcaccatcaggcggcggccctcggcggcgcgcttgaggccgtcgaaccactccggggccatgatgttgggcaggctgccgatcagcggctggatcagcaggccgtcagccacggcttgccgttcctcggcgctgaggtgcgccccaagggcgtgcaggcggtgatgaatggcggtgggcgggtcttcggcgggcaggtagatcaccgggccggtgggcagttcgcccacctccagcagatccggcccgcctgcaatctgtgcggccagttgcagggccagcatggatttaccggcaccaccgggcgacaccagcgccccgaccgtaccggccaccatgttgggcaaaacgtagtccagcggtggcggcgctgctgcgaacgcctccagaatattgataggcttatgggtagccattgattgcctcctttgcaggcagttggtggttaggcgctggcggggtcactacccccgccctgcgccgctctgagttcttccaggcactcgcgcagcgcctcgtattcgtcgtcggtcagccagaacttgcgctgacgcatccctttggccttcatgcgctcggcatatcgcgcttggcgtacagcgtcagggctggccagcaggtcgccggtctgcttgtccttttggtctttcatatcagtcaccgagaaacttgccggggccgaaaggcttgtcttcgcggaacaaggacaaggtgcagccgtcaaggttaaggctggccatatcagcgactgaaaagcggccagcctcggccttgtttgacgtataaccaaagccaccgggcaaccaatagcccttgtcacttttgatcaggtagaccgaccctgaagcgcttttttcgtattccataaaacccccttctgtgcgtgagtactcatagtataacaggcgtgagtaccaacgcaagcactacatgctgaaatctggcccgcccctgtccatgcctcgctggcggggtgccggtgcccgtgccagctcggcccgcgcaagctggacgctgggcagacccatgaccttgctgacggtgcgctcgatgtaatccgcttcgtggccgggcttgcgctctgccagcgctgggctggcctcggccatggccttgccgatttcctcggcactgcggccccggctggccagcttctgcgcggcgataaagtcgcacttgctgaggtcatcaccgaagcgcttgaccagcccggccatctcgctgcggtactcgtccagcgccgtgcgccggtggcggctaagctgccgctcgggcagttcgaggctggccagcctgcgggccttctcctgctgccgctgggcctgctcgatctgctggccagcctgctgcaccagcgccgggccagcggtggcggtcttgcccttggattcacgcagcagcacccacggctgataaccggcgcgggtggtgtgcttgtccttgcggttggtgaagcccgccaagcggccatagtggcggctgtcggcgctggccgggtcggcgtcgtactcgctggccagcgtccgggcaatctgcccccgaagttcaccgcctgcggcgtcggccaccttgacccatgcctgatagttcttcgggctggtttccactaccagggcaggctcccggccctcggctttcatgtcatccaggtcaaactcgctgaggtcgtccaccagcaccagaccatgccgctcctgctcggcgggcctgatatacacgtcattgccctgggcattcatccgcttgagccatggcgtgttctggagcacttcggcggctgaccattcccggttcatcatctggccggtggtggcgtccctgacgccgatatcgaagcgctcacagcccatggccttgagctgtcggcctatggcctgcaaagtcctgtcgttcttcatcgggccaccaagcgattcccacacattatacgagccggaagcataaagtgtaaagcctagatccgaaggatgagccgggctgaatgatcgaccgagacaggccctgcggggctgcacacgcgcccccacccttcgggtagggggaaaggccgctaaagcggctaaaagcgctccagcgtatttctgcggggtttggtgtggggtttagcgggctttgcccgcctttccccctgccgcgcagcggtggggcggtgtgtagcctagcgcagcgaatagaccagctatccggcctctggccgggcatattgggcaagggcagcagcgccccacaagggcgctgataaccgcgcctagtggattattcttagataatcatggatggatttttccaacaccccgccagcccccgcccctgctgggtttgcaggtttgggggcgtgacagttattgcaggggttcgtgacagttattgcaggggggcgtgacagttattgcaggggttcgtgacagttagggcgcgcccagctgtctagggcggcggatttgtcctactcaggagagcgttcaccgacaaacaacagataaaacgaaaggcccagtctttcgactgagcctttcgttttatttgatgcctGCTCTTCT"), strings.ToUpper("ATGatatatatatata")},
		Stickyends_5prime: []string{"GGT", "ATG"},
		Stickyends_3prime: []string{"", ""},
	},
	// BsaI is a non cutter
	digesttest{
		sequence:          pSEVA651,
		enzyme:            BsaI.RestrictionEnzyme,
		doublestranded:    []wtype.DNASequence{
		{Nm: "Fwdsequence", 
		Seq: strings.ToUpper("ttaattaaagcggataacaatttcacacaggaggccgcctaggccgcggccgcgcgaattcgagctcggtacccggggatcctctagagtcgacctgcaggcatgcaagcttgcggccgcgtcgtgactgggaaaaccctggcgactagtcttggactcctgttgatagatccagtaatgacctcagaactccatctggatttgttcagaacgctcggttgccgccgggcgttttttattggtgagaatccaggggtccccaataattacgatttaaatttgacataagcctgttcggttcgtaaactgtaatgcaagtagcgtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttgtacagcctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaggtggctcaagtatgggcatcattcgcacatgtaggctcggccctgaccaagtcaaatccatgcgggctgctcttgatcttttcggtcgtgagttcggagacgtagccacctactcccaacatcagccggactccgattacctcgggaacttgctccgtagtaagacattcatcgcgcttgctgccttcgaccaagaagcggttgttggcgctctcgcggcttacgttctgcccaagtttgagcagccgcgtagtgagatctatatctatgatctcgcagtctccggagagcaccggaggcagggcattgccaccgcgctcatcaatctcctcaagcatgaggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtgatgcactttgatatcgacccaagtaccgccacctaacaattcgttcaagccgagatcggcttcccggccgcggagttgttcggtaaattggacaacggtccgcgcgttgtccttttccgctgcataaccctgcttcggggtcattatagcgattttttcggtatatccatcctttttcgcacgatatacaggattttgccaaagggttcgtgtagactttccttggtgtatccaacggcgtcagccgggcaggataggtgaagtaggcccacccgcgagcgggtgttccttcttcactgtcccttattcgcacctggcggtgctcaacgggaatcctgctctgcgaggctggccgtaggccggcctcagcctgccgccttgggccgggtgatgtcgtacttgcccgccgcgaactcggttaccgtccagcccagcgcgaccagctccggcaacgcctcgcgcacccgctggcggcgcttgcgcatggtcgaaccactggcctctgacggccagacatagccgcacaaggtatctatggaagccttgccggttttgccggggtcgatccagccacacagccgctggtgcagcaggcgggcggtttcgctgtccagcgcccgcacctcgtccatgctgatgcgcacatgctggccgccacccatgacggcctgcgcgatcaaggggttcagggccacgtacaggcgcccgtccgcctcgtcgctggcgtactccgacagcagccgaaacccctgccgcttgcggccattctgggcgatgatggataccttccaaaggcgctcgatgcagtcctgtatgtgcttgagcgccccaccactatcgacctctgccccgatttcctttgccagcgcccgatagctacctttgaccacatggcattcagcggtgacggcctcccacttgggttccaggaacagccggagctgccgtccgccttcggtcttgggttccgggccaagcactaggccattaggcccagccatggccaccagcccttgcaggatgcgcagatcatcagcgcccagcggctccgggccgctgaactcgatccgcttgccgtcgccgtagtcatacgtcacgtccagcttgctgcgcttgcgctcgccccgcttgagggcacggaacaggccgggggccagacagtgcgccgggtcgtgccggacgtggctgaggctgtgcttgttcttaggcttcaccacggggcacccccttgctcttgcgctgcctctccagcacggcgggcttgagcaccccgccgtcatgccgcctgaaccaccgatcagcgaacggtgcgccatagttggccttgctcacaccgaagcggacgaagaaccggcgctggtcgtcgtccacaccccattcctcggcctcggcgctggtcatgctcgacaggtaggactgccagcggatgttatcgaccagtaccgagctgccccggctggcctgctgctggtcgcctgcgcccatcatggccgcgcccttgctggcatggtgcaggaacacgatagagcacccggtatcggcggcgatggcctccatgcgaccgatgacctgggccatggggccgctggcgttttcttcctcgatgtggaaccggcgcagcgtgtccagcaccatcaggcggcggccctcggcggcgcgcttgaggccgtcgaaccactccggggccatgatgttgggcaggctgccgatcagcggctggatcagcaggccgtcagccacggcttgccgttcctcggcgctgaggtgcgccccaagggcgtgcaggcggtgatgaatggcggtgggcgggtcttcggcgggcaggtagatcaccgggccggtgggcagttcgcccacctccagcagatccggcccgcctgcaatctgtgcggccagttgcagggccagcatggatttaccggcaccaccgggcgacaccagcgccccgaccgtaccggccaccatgttgggcaaaacgtagtccagcggtggcggcgctgctgcgaacgcctccagaatattgataggcttatgggtagccattgattgcctcctttgcaggcagttggtggttaggcgctggcggggtcactacccccgccctgcgccgctctgagttcttccaggcactcgcgcagcgcctcgtattcgtcgtcggtcagccagaacttgcgctgacgcatccctttggccttcatgcgctcggcatatcgcgcttggcgtacagcgtcagggctggccagcaggtcgccggtctgcttgtccttttggtctttcatatcagtcaccgagaaacttgccggggccgaaaggcttgtcttcgcggaacaaggacaaggtgcagccgtcaaggttaaggctggccatatcagcgactgaaaagcggccagcctcggccttgtttgacgtataaccaaagccaccgggcaaccaatagcccttgtcacttttgatcaggtagaccgaccctgaagcgcttttttcgtattccataaaacccccttctgtgcgtgagtactcatagtataacaggcgtgagtaccaacgcaagcactacatgctgaaatctggcccgcccctgtccatgcctcgctggcggggtgccggtgcccgtgccagctcggcccgcgcaagctggacgctgggcagacccatgaccttgctgacggtgcgctcgatgtaatccgcttcgtggccgggcttgcgctctgccagcgctgggctggcctcggccatggccttgccgatttcctcggcactgcggccccggctggccagcttctgcgcggcgataaagtcgcacttgctgaggtcatcaccgaagcgcttgaccagcccggccatctcgctgcggtactcgtccagcgccgtgcgccggtggcggctaagctgccgctcgggcagttcgaggctggccagcctgcgggccttctcctgctgccgctgggcctgctcgatctgctggccagcctgctgcaccagcgccgggccagcggtggcggtcttgcccttggattcacgcagcagcacccacggctgataaccggcgcgggtggtgtgcttgtccttgcggttggtgaagcccgccaagcggccatagtggcggctgtcggcgctggccgggtcggcgtcgtactcgctggccagcgtccgggcaatctgcccccgaagttcaccgcctgcggcgtcggccaccttgacccatgcctgatagttcttcgggctggtttccactaccagggcaggctcccggccctcggctttcatgtcatccaggtcaaactcgctgaggtcgtccaccagcaccagaccatgccgctcctgctcggcgggcctgatatacacgtcattgccctgggcattcatccgcttgagccatggcgtgttctggagcacttcggcggctgaccattcccggttcatcatctggccggtggtggcgtccctgacgccgatatcgaagcgctcacagcccatggccttgagctgtcggcctatggcctgcaaagtcctgtcgttcttcatcgggccaccaagcgattcccacacattatacgagccggaagcataaagtgtaaagcctagatccgaaggatgagccgggctgaatgatcgaccgagacaggccctgcggggctgcacacgcgcccccacccttcgggtagggggaaaggccgctaaagcggctaaaagcgctccagcgtatttctgcggggtttggtgtggggtttagcgggctttgcccgcctttccccctgccgcgcagcggtggggcggtgtgtagcctagcgcagcgaatagaccagctatccggcctctggccgggcatattgggcaagggcagcagcgccccacaagggcgctgataaccgcgcctagtggattattcttagataatcatggatggatttttccaacaccccgccagcccccgcccctgctgggtttgcaggtttgggggcgtgacagttattgcaggggttcgtgacagttattgcaggggggcgtgacagttattgcaggggttcgtgacagttagggcgcgcccagctgtctagggcggcggatttgtcctactcaggagagcgttcaccgacaaacaacagataaaacgaaaggcccagtctttcgactgagcctttcgttttatttgatgcctGCTCTTCTATGatatatatatataGGTAGAAGAGC"),
		Plasmid: true,
		}, 
		{Nm: "Reversecomplement", 
		Seq: strings.ToUpper("GCTCTTCTACCtatatatatatatCATAGAAGAGCaggcatcaaataaaacgaaaggctcagtcgaaagactgggcctttcgttttatctgttgtttgtcggtgaacgctctcctgagtaggacaaatccgccgccctagacagctgggcgcgccctaactgtcacgaacccctgcaataactgtcacgcccccctgcaataactgtcacgaacccctgcaataactgtcacgcccccaaacctgcaaacccagcaggggcgggggctggcggggtgttggaaaaatccatccatgattatctaagaataatccactaggcgcggttatcagcgcccttgtggggcgctgctgcccttgcccaatatgcccggccagaggccggatagctggtctattcgctgcgctaggctacacaccgccccaccgctgcgcggcagggggaaaggcgggcaaagcccgctaaaccccacaccaaaccccgcagaaatacgctggagcgcttttagccgctttagcggcctttccccctacccgaagggtgggggcgcgtgtgcagccccgcagggcctgtctcggtcgatcattcagcccggctcatccttcggatctaggctttacactttatgcttccggctcgtataatgtgtgggaatcgcttggtggcccgatgaagaacgacaggactttgcaggccataggccgacagctcaaggccatgggctgtgagcgcttcgatatcggcgtcagggacgccaccaccggccagatgatgaaccgggaatggtcagccgccgaagtgctccagaacacgccatggctcaagcggatgaatgcccagggcaatgacgtgtatatcaggcccgccgagcaggagcggcatggtctggtgctggtggacgacctcagcgagtttgacctggatgacatgaaagccgagggccgggagcctgccctggtagtggaaaccagcccgaagaactatcaggcatgggtcaaggtggccgacgccgcaggcggtgaacttcgggggcagattgcccggacgctggccagcgagtacgacgccgacccggccagcgccgacagccgccactatggccgcttggcgggcttcaccaaccgcaaggacaagcacaccacccgcgccggttatcagccgtgggtgctgctgcgtgaatccaagggcaagaccgccaccgctggcccggcgctggtgcagcaggctggccagcagatcgagcaggcccagcggcagcaggagaaggcccgcaggctggccagcctcgaactgcccgagcggcagcttagccgccaccggcgcacggcgctggacgagtaccgcagcgagatggccgggctggtcaagcgcttcggtgatgacctcagcaagtgcgactttatcgccgcgcagaagctggccagccggggccgcagtgccgaggaaatcggcaaggccatggccgaggccagcccagcgctggcagagcgcaagcccggccacgaagcggattacatcgagcgcaccgtcagcaaggtcatgggtctgcccagcgtccagcttgcgcgggccgagctggcacgggcaccggcaccccgccagcgaggcatggacaggggcgggccagatttcagcatgtagtgcttgcgttggtactcacgcctgttatactatgagtactcacgcacagaagggggttttatggaatacgaaaaaagcgcttcagggtcggtctacctgatcaaaagtgacaagggctattggttgcccggtggctttggttatacgtcaaacaaggccgaggctggccgcttttcagtcgctgatatggccagccttaaccttgacggctgcaccttgtccttgttccgcgaagacaagcctttcggccccggcaagtttctcggtgactgatatgaaagaccaaaaggacaagcagaccggcgacctgctggccagccctgacgctgtacgccaagcgcgatatgccgagcgcatgaaggccaaagggatgcgtcagcgcaagttctggctgaccgacgacgaatacgaggcgctgcgcgagtgcctggaagaactcagagcggcgcagggcgggggtagtgaccccgccagcgcctaaccaccaactgcctgcaaaggaggcaatcaatggctacccataagcctatcaatattctggaggcgttcgcagcagcgccgccaccgctggactacgttttgcccaacatggtggccggtacggtcggggcgctggtgtcgcccggtggtgccggtaaatccatgctggccctgcaactggccgcacagattgcaggcgggccggatctgctggaggtgggcgaactgcccaccggcccggtgatctacctgcccgccgaagacccgcccaccgccattcatcaccgcctgcacgcccttggggcgcacctcagcgccgaggaacggcaagccgtggctgacggcctgctgatccagccgctgatcggcagcctgcccaacatcatggccccggagtggttcgacggcctcaagcgcgccgccgagggccgccgcctgatggtgctggacacgctgcgccggttccacatcgaggaagaaaacgccagcggccccatggcccaggtcatcggtcgcatggaggccatcgccgccgataccgggtgctctatcgtgttcctgcaccatgccagcaagggcgcggccatgatgggcgcaggcgaccagcagcaggccagccggggcagctcggtactggtcgataacatccgctggcagtcctacctgtcgagcatgaccagcgccgaggccgaggaatggggtgtggacgacgaccagcgccggttcttcgtccgcttcggtgtgagcaaggccaactatggcgcaccgttcgctgatcggtggttcaggcggcatgacggcggggtgctcaagcccgccgtgctggagaggcagcgcaagagcaagggggtgccccgtggtgaagcctaagaacaagcacagcctcagccacgtccggcacgacccggcgcactgtctggcccccggcctgttccgtgccctcaagcggggcgagcgcaagcgcagcaagctggacgtgacgtatgactacggcgacggcaagcggatcgagttcagcggcccggagccgctgggcgctgatgatctgcgcatcctgcaagggctggtggccatggctgggcctaatggcctagtgcttggcccggaacccaagaccgaaggcggacggcagctccggctgttcctggaacccaagtgggaggccgtcaccgctgaatgccatgtggtcaaaggtagctatcgggcgctggcaaaggaaatcggggcagaggtcgatagtggtggggcgctcaagcacatacaggactgcatcgagcgcctttggaaggtatccatcatcgcccagaatggccgcaagcggcaggggtttcggctgctgtcggagtacgccagcgacgaggcggacgggcgcctgtacgtggccctgaaccccttgatcgcgcaggccgtcatgggtggcggccagcatgtgcgcatcagcatggacgaggtgcgggcgctggacagcgaaaccgcccgcctgctgcaccagcggctgtgtggctggatcgaccccggcaaaaccggcaaggcttccatagataccttgtgcggctatgtctggccgtcagaggccagtggttcgaccatgcgcaagcgccgccagcgggtgcgcgaggcgttgccggagctggtcgcgctgggctggacggtaaccgagttcgcggcgggcaagtacgacatcacccggcccaaggcggcaggctgaggccggcctacggccagcctcgcagagcaggattcccgttgagcaccgccaggtgcgaataagggacagtgaagaaggaacacccgctcgcgggtgggcctacttcacctatcctgcccggctgacgccgttggatacaccaaggaaagtctacacgaaccctttggcaaaatcctgtatatcgtgcgaaaaaggatggatataccgaaaaaatcgctataatgaccccgaagcagggttatgcagcggaaaaggacaacgcgcggaccgttgtccaatttaccgaacaactccgcggccgggaagccgatctcggcttgaacgaattgttaggtggcggtacttgggtcgatatcaaagtgcatcacttcttcccgtatgcccaactttgtatagagagccactgcgggatcgtcaccgtaatctgcttgcacgtagatcacataagcaccaagcgcgttggcctcatgcttgaggagattgatgagcgcggtggcaatgccctgcctccggtgctctccggagactgcgagatcatagatatagatctcactacgcggctgctcaaacttgggcagaacgtaagccgcgagagcgccaacaaccgcttcttggtcgaaggcagcaagcgcgatgaatgtcttactacggagcaagttcccgaggtaatcggagtccggctgatgttgggagtaggtggctacgtctccgaactcacgaccgaaaagatcaagagcagcccgcatggatttgacttggtcagggccgagcctacatgtgcgaatgatgcccatacttgagccacctaactttgttttagggcgactgccctgctgcgtaacatcgttgctgctgcgtaacatcgttgctgctccataacatcaaacatcgacccacggcgtaacgcgcttgctgcttggatgcccgaggcataggctgtacaaaaaaacagtcataacaagccatgaaaaccgccactgcgccgttaccaccgctgcgttcggtcaaggttctggaccagttgcgtgagcgcatacgctacttgcattacagtttacgaaccgaacaggcttatgtcaaatttaaatcgtaattattggggacccctggattctcaccaataaaaaacgcccggcggcaaccgagcgttctgaacaaatccagatggagttctgaggtcattactggatctatcaacaggagtccaagactagtcgccagggttttcccagtcacgacgcggccgcaagcttgcatgcctgcaggtcgactctagaggatccccgggtaccgagctcgaattcgcgcggccgcggcctaggcggcctcctgtgtgaaattgttatccgctttaattaa"),
		Plasmid: true,
		},
		},
		Finalfragments:    []string{strings.ToUpper("ttaattaaagcggataacaatttcacacaggaggccgcctaggccgcggccgcgcgaattcgagctcggtacccggggatcctctagagtcgacctgcaggcatgcaagcttgcggccgcgtcgtgactgggaaaaccctggcgactagtcttggactcctgttgatagatccagtaatgacctcagaactccatctggatttgttcagaacgctcggttgccgccgggcgttttttattggtgagaatccaggggtccccaataattacgatttaaatttgacataagcctgttcggttcgtaaactgtaatgcaagtagcgtatgcgctcacgcaactggtccagaaccttgaccgaacgcagcggtggtaacggcgcagtggcggttttcatggcttgttatgactgtttttttgtacagcctatgcctcgggcatccaagcagcaagcgcgttacgccgtgggtcgatgtttgatgttatggagcagcaacgatgttacgcagcagcaacgatgttacgcagcagggcagtcgccctaaaacaaagttaggtggctcaagtatgggcatcattcgcacatgtaggctcggccctgaccaagtcaaatccatgcgggctgctcttgatcttttcggtcgtgagttcggagacgtagccacctactcccaacatcagccggactccgattacctcgggaacttgctccgtagtaagacattcatcgcgcttgctgccttcgaccaagaagcggttgttggcgctctcgcggcttacgttctgcccaagtttgagcagccgcgtagtgagatctatatctatgatctcgcagtctccggagagcaccggaggcagggcattgccaccgcgctcatcaatctcctcaagcatgaggccaacgcgcttggtgcttatgtgatctacgtgcaagcagattacggtgacgatcccgcagtggctctctatacaaagttgggcatacgggaagaagtgatgcactttgatatcgacccaagtaccgccacctaacaattcgttcaagccgagatcggcttcccggccgcggagttgttcggtaaattggacaacggtccgcgcgttgtccttttccgctgcataaccctgcttcggggtcattatagcgattttttcggtatatccatcctttttcgcacgatatacaggattttgccaaagggttcgtgtagactttccttggtgtatccaacggcgtcagccgggcaggataggtgaagtaggcccacccgcgagcgggtgttccttcttcactgtcccttattcgcacctggcggtgctcaacgggaatcctgctctgcgaggctggccgtaggccggcctcagcctgccgccttgggccgggtgatgtcgtacttgcccgccgcgaactcggttaccgtccagcccagcgcgaccagctccggcaacgcctcgcgcacccgctggcggcgcttgcgcatggtcgaaccactggcctctgacggccagacatagccgcacaaggtatctatggaagccttgccggttttgccggggtcgatccagccacacagccgctggtgcagcaggcgggcggtttcgctgtccagcgcccgcacctcgtccatgctgatgcgcacatgctggccgccacccatgacggcctgcgcgatcaaggggttcagggccacgtacaggcgcccgtccgcctcgtcgctggcgtactccgacagcagccgaaacccctgccgcttgcggccattctgggcgatgatggataccttccaaaggcgctcgatgcagtcctgtatgtgcttgagcgccccaccactatcgacctctgccccgatttcctttgccagcgcccgatagctacctttgaccacatggcattcagcggtgacggcctcccacttgggttccaggaacagccggagctgccgtccgccttcggtcttgggttccgggccaagcactaggccattaggcccagccatggccaccagcccttgcaggatgcgcagatcatcagcgcccagcggctccgggccgctgaactcgatccgcttgccgtcgccgtagtcatacgtcacgtccagcttgctgcgcttgcgctcgccccgcttgagggcacggaacaggccgggggccagacagtgcgccgggtcgtgccggacgtggctgaggctgtgcttgttcttaggcttcaccacggggcacccccttgctcttgcgctgcctctccagcacggcgggcttgagcaccccgccgtcatgccgcctgaaccaccgatcagcgaacggtgcgccatagttggccttgctcacaccgaagcggacgaagaaccggcgctggtcgtcgtccacaccccattcctcggcctcggcgctggtcatgctcgacaggtaggactgccagcggatgttatcgaccagtaccgagctgccccggctggcctgctgctggtcgcctgcgcccatcatggccgcgcccttgctggcatggtgcaggaacacgatagagcacccggtatcggcggcgatggcctccatgcgaccgatgacctgggccatggggccgctggcgttttcttcctcgatgtggaaccggcgcagcgtgtccagcaccatcaggcggcggccctcggcggcgcgcttgaggccgtcgaaccactccggggccatgatgttgggcaggctgccgatcagcggctggatcagcaggccgtcagccacggcttgccgttcctcggcgctgaggtgcgccccaagggcgtgcaggcggtgatgaatggcggtgggcgggtcttcggcgggcaggtagatcaccgggccggtgggcagttcgcccacctccagcagatccggcccgcctgcaatctgtgcggccagttgcagggccagcatggatttaccggcaccaccgggcgacaccagcgccccgaccgtaccggccaccatgttgggcaaaacgtagtccagcggtggcggcgctgctgcgaacgcctccagaatattgataggcttatgggtagccattgattgcctcctttgcaggcagttggtggttaggcgctggcggggtcactacccccgccctgcgccgctctgagttcttccaggcactcgcgcagcgcctcgtattcgtcgtcggtcagccagaacttgcgctgacgcatccctttggccttcatgcgctcggcatatcgcgcttggcgtacagcgtcagggctggccagcaggtcgccggtctgcttgtccttttggtctttcatatcagtcaccgagaaacttgccggggccgaaaggcttgtcttcgcggaacaaggacaaggtgcagccgtcaaggttaaggctggccatatcagcgactgaaaagcggccagcctcggccttgtttgacgtataaccaaagccaccgggcaaccaatagcccttgtcacttttgatcaggtagaccgaccctgaagcgcttttttcgtattccataaaacccccttctgtgcgtgagtactcatagtataacaggcgtgagtaccaacgcaagcactacatgctgaaatctggcccgcccctgtccatgcctcgctggcggggtgccggtgcccgtgccagctcggcccgcgcaagctggacgctgggcagacccatgaccttgctgacggtgcgctcgatgtaatccgcttcgtggccgggcttgcgctctgccagcgctgggctggcctcggccatggccttgccgatttcctcggcactgcggccccggctggccagcttctgcgcggcgataaagtcgcacttgctgaggtcatcaccgaagcgcttgaccagcccggccatctcgctgcggtactcgtccagcgccgtgcgccggtggcggctaagctgccgctcgggcagttcgaggctggccagcctgcgggccttctcctgctgccgctgggcctgctcgatctgctggccagcctgctgcaccagcgccgggccagcggtggcggtcttgcccttggattcacgcagcagcacccacggctgataaccggcgcgggtggtgtgcttgtccttgcggttggtgaagcccgccaagcggccatagtggcggctgtcggcgctggccgggtcggcgtcgtactcgctggccagcgtccgggcaatctgcccccgaagttcaccgcctgcggcgtcggccaccttgacccatgcctgatagttcttcgggctggtttccactaccagggcaggctcccggccctcggctttcatgtcatccaggtcaaactcgctgaggtcgtccaccagcaccagaccatgccgctcctgctcggcgggcctgatatacacgtcattgccctgggcattcatccgcttgagccatggcgtgttctggagcacttcggcggctgaccattcccggttcatcatctggccggtggtggcgtccctgacgccgatatcgaagcgctcacagcccatggccttgagctgtcggcctatggcctgcaaagtcctgtcgttcttcatcgggccaccaagcgattcccacacattatacgagccggaagcataaagtgtaaagcctagatccgaaggatgagccgggctgaatgatcgaccgagacaggccctgcggggctgcacacgcgcccccacccttcgggtagggggaaaggccgctaaagcggctaaaagcgctccagcgtatttctgcggggtttggtgtggggtttagcgggctttgcccgcctttccccctgccgcgcagcggtggggcggtgtgtagcctagcgcagcgaatagaccagctatccggcctctggccgggcatattgggcaagggcagcagcgccccacaagggcgctgataaccgcgcctagtggattattcttagataatcatggatggatttttccaacaccccgccagcccccgcccctgctgggtttgcaggtttgggggcgtgacagttattgcaggggttcgtgacagttattgcaggggggcgtgacagttattgcaggggttcgtgacagttagggcgcgcccagctgtctagggcggcggatttgtcctactcaggagagcgttcaccgacaaacaacagataaaacgaaaggcccagtctttcgactgagcctttcgttttatttgatgcctGCTCTTCTATGatatatatatataGGTAGAAGAGC")},
		Stickyends_5prime: []string{"blunt"},
		Stickyends_3prime: []string{""},
	},
}

func TestDigest(t *testing.T) {
	for _, test := range digesttests {
		fragments, fivePrimeStickyEnds, threePrimeStickeyEnds := Digest(test.sequence, test.enzyme)
		for i := 0; i < len(fragments); i++ {
			if fragments[i] != test.Finalfragments[i] {
				t.Error(
					"For", test.sequence.Name(), "\n",
					"and", test.enzyme.Name(), "\n",
					"expected", test.Finalfragments[i], "\n",
					"got", fragments[i], "\n",
				)
			}
		}
		for i := 0; i < len(fivePrimeStickyEnds); i++ {
			if fivePrimeStickyEnds[i] != test.Stickyends_5prime[i] {
				t.Error(
					"For", test.sequence.Name(), "\n",
					"and", test.enzyme.Name(), "\n",
					"expected", test.Stickyends_5prime[i], "\n",
					"got", fivePrimeStickyEnds[i], "\n",
				)
			}
		}
		for i := 0; i < len(threePrimeStickeyEnds); i++ {
			if threePrimeStickeyEnds[i] != test.Stickyends_3prime[i] {
				t.Error(
					"For", test.sequence.Name(), "\n",
					"and", test.enzyme.Name(), "\n",
					"expected", test.Stickyends_3prime[i], "\n",
					"got", threePrimeStickeyEnds[i], "\n",
				)
			}
		}
	}
}

// simple reverse complement check to test testing methodology initially
type testsequence struct {
	sequence string
	revcomp  string
}

var seqs = []testsequence{
	{"ATG", "CAT"},
	{"YNB", "VNR"},
}

func TestRevComp(t *testing.T) {
	for _, sequence := range seqs {
		r := wtype.RevComp(sequence.sequence)
		if r != sequence.revcomp {
			t.Error(
				"For", sequence.sequence, "/n",
				"expected", sequence.revcomp, "\n",
				"got", r, "\n",
			)
		}
	}

}

func TestMakedoublestrandedDNA(t *testing.T) {
	for _, sequence := range digesttests {
		doubleStrandedDNA := MakedoublestrandedDNA(sequence.sequence)
		for i := 0; i < len(doubleStrandedDNA); i++ {
			if !reflect.DeepEqual(doubleStrandedDNA[i],sequence.doublestranded[i]) {
				t.Error(
					"For", sequence.sequence, "\n",
					"expected", sequence.doublestranded[i], "\n",
					"got", doubleStrandedDNA[i], "\n",
				)
			}
		}
	}
}

type assemblytest struct {
	parts                  []wtype.DNASequence
	vector                 wtype.DNASequence
	enzyme                 wtype.TypeIIs
	desiredassemblyproduct wtype.DNASequence
}

var assemblytests = []assemblytest{
	{[]wtype.DNASequence{comet1part},
		pSEVA651,
		SapI,
		wtype.DNASequence{
		Nm: "simulated assembly sequence", 
		Seq: "TTAATTAAAGCGGATAACAATTTCACACAGGAGGCCGCCTAGGCCGCGGCCGCGCGAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTTGCGGCCGCGTCGTGACTGGGAAAACCCTGGCGACTAGTCTTGGACTCCTGTTGATAGATCCAGTAATGACCTCAGAACTCCATCTGGATTTGTTCAGAACGCTCGGTTGCCGCCGGGCGTTTTTTATTGGTGAGAATCCAGGGGTCCCCAATAATTACGATTTAAATTTGACATAAGCCTGTTCGGTTCGTAAACTGTAATGCAAGTAGCGTATGCGCTCACGCAACTGGTCCAGAACCTTGACCGAACGCAGCGGTGGTAACGGCGCAGTGGCGGTTTTCATGGCTTGTTATGACTGTTTTTTTGTACAGCCTATGCCTCGGGCATCCAAGCAGCAAGCGCGTTACGCCGTGGGTCGATGTTTGATGTTATGGAGCAGCAACGATGTTACGCAGCAGCAACGATGTTACGCAGCAGGGCAGTCGCCCTAAAACAAAGTTAGGTGGCTCAAGTATGGGCATCATTCGCACATGTAGGCTCGGCCCTGACCAAGTCAAATCCATGCGGGCTGCTCTTGATCTTTTCGGTCGTGAGTTCGGAGACGTAGCCACCTACTCCCAACATCAGCCGGACTCCGATTACCTCGGGAACTTGCTCCGTAGTAAGACATTCATCGCGCTTGCTGCCTTCGACCAAGAAGCGGTTGTTGGCGCTCTCGCGGCTTACGTTCTGCCCAAGTTTGAGCAGCCGCGTAGTGAGATCTATATCTATGATCTCGCAGTCTCCGGAGAGCACCGGAGGCAGGGCATTGCCACCGCGCTCATCAATCTCCTCAAGCATGAGGCCAACGCGCTTGGTGCTTATGTGATCTACGTGCAAGCAGATTACGGTGACGATCCCGCAGTGGCTCTCTATACAAAGTTGGGCATACGGGAAGAAGTGATGCACTTTGATATCGACCCAAGTACCGCCACCTAACAATTCGTTCAAGCCGAGATCGGCTTCCCGGCCGCGGAGTTGTTCGGTAAATTGGACAACGGTCCGCGCGTTGTCCTTTTCCGCTGCATAACCCTGCTTCGGGGTCATTATAGCGATTTTTTCGGTATATCCATCCTTTTTCGCACGATATACAGGATTTTGCCAAAGGGTTCGTGTAGACTTTCCTTGGTGTATCCAACGGCGTCAGCCGGGCAGGATAGGTGAAGTAGGCCCACCCGCGAGCGGGTGTTCCTTCTTCACTGTCCCTTATTCGCACCTGGCGGTGCTCAACGGGAATCCTGCTCTGCGAGGCTGGCCGTAGGCCGGCCTCAGCCTGCCGCCTTGGGCCGGGTGATGTCGTACTTGCCCGCCGCGAACTCGGTTACCGTCCAGCCCAGCGCGACCAGCTCCGGCAACGCCTCGCGCACCCGCTGGCGGCGCTTGCGCATGGTCGAACCACTGGCCTCTGACGGCCAGACATAGCCGCACAAGGTATCTATGGAAGCCTTGCCGGTTTTGCCGGGGTCGATCCAGCCACACAGCCGCTGGTGCAGCAGGCGGGCGGTTTCGCTGTCCAGCGCCCGCACCTCGTCCATGCTGATGCGCACATGCTGGCCGCCACCCATGACGGCCTGCGCGATCAAGGGGTTCAGGGCCACGTACAGGCGCCCGTCCGCCTCGTCGCTGGCGTACTCCGACAGCAGCCGAAACCCCTGCCGCTTGCGGCCATTCTGGGCGATGATGGATACCTTCCAAAGGCGCTCGATGCAGTCCTGTATGTGCTTGAGCGCCCCACCACTATCGACCTCTGCCCCGATTTCCTTTGCCAGCGCCCGATAGCTACCTTTGACCACATGGCATTCAGCGGTGACGGCCTCCCACTTGGGTTCCAGGAACAGCCGGAGCTGCCGTCCGCCTTCGGTCTTGGGTTCCGGGCCAAGCACTAGGCCATTAGGCCCAGCCATGGCCACCAGCCCTTGCAGGATGCGCAGATCATCAGCGCCCAGCGGCTCCGGGCCGCTGAACTCGATCCGCTTGCCGTCGCCGTAGTCATACGTCACGTCCAGCTTGCTGCGCTTGCGCTCGCCCCGCTTGAGGGCACGGAACAGGCCGGGGGCCAGACAGTGCGCCGGGTCGTGCCGGACGTGGCTGAGGCTGTGCTTGTTCTTAGGCTTCACCACGGGGCACCCCCTTGCTCTTGCGCTGCCTCTCCAGCACGGCGGGCTTGAGCACCCCGCCGTCATGCCGCCTGAACCACCGATCAGCGAACGGTGCGCCATAGTTGGCCTTGCTCACACCGAAGCGGACGAAGAACCGGCGCTGGTCGTCGTCCACACCCCATTCCTCGGCCTCGGCGCTGGTCATGCTCGACAGGTAGGACTGCCAGCGGATGTTATCGACCAGTACCGAGCTGCCCCGGCTGGCCTGCTGCTGGTCGCCTGCGCCCATCATGGCCGCGCCCTTGCTGGCATGGTGCAGGAACACGATAGAGCACCCGGTATCGGCGGCGATGGCCTCCATGCGACCGATGACCTGGGCCATGGGGCCGCTGGCGTTTTCTTCCTCGATGTGGAACCGGCGCAGCGTGTCCAGCACCATCAGGCGGCGGCCCTCGGCGGCGCGCTTGAGGCCGTCGAACCACTCCGGGGCCATGATGTTGGGCAGGCTGCCGATCAGCGGCTGGATCAGCAGGCCGTCAGCCACGGCTTGCCGTTCCTCGGCGCTGAGGTGCGCCCCAAGGGCGTGCAGGCGGTGATGAATGGCGGTGGGCGGGTCTTCGGCGGGCAGGTAGATCACCGGGCCGGTGGGCAGTTCGCCCACCTCCAGCAGATCCGGCCCGCCTGCAATCTGTGCGGCCAGTTGCAGGGCCAGCATGGATTTACCGGCACCACCGGGCGACACCAGCGCCCCGACCGTACCGGCCACCATGTTGGGCAAAACGTAGTCCAGCGGTGGCGGCGCTGCTGCGAACGCCTCCAGAATATTGATAGGCTTATGGGTAGCCATTGATTGCCTCCTTTGCAGGCAGTTGGTGGTTAGGCGCTGGCGGGGTCACTACCCCCGCCCTGCGCCGCTCTGAGTTCTTCCAGGCACTCGCGCAGCGCCTCGTATTCGTCGTCGGTCAGCCAGAACTTGCGCTGACGCATCCCTTTGGCCTTCATGCGCTCGGCATATCGCGCTTGGCGTACAGCGTCAGGGCTGGCCAGCAGGTCGCCGGTCTGCTTGTCCTTTTGGTCTTTCATATCAGTCACCGAGAAACTTGCCGGGGCCGAAAGGCTTGTCTTCGCGGAACAAGGACAAGGTGCAGCCGTCAAGGTTAAGGCTGGCCATATCAGCGACTGAAAAGCGGCCAGCCTCGGCCTTGTTTGACGTATAACCAAAGCCACCGGGCAACCAATAGCCCTTGTCACTTTTGATCAGGTAGACCGACCCTGAAGCGCTTTTTTCGTATTCCATAAAACCCCCTTCTGTGCGTGAGTACTCATAGTATAACAGGCGTGAGTACCAACGCAAGCACTACATGCTGAAATCTGGCCCGCCCCTGTCCATGCCTCGCTGGCGGGGTGCCGGTGCCCGTGCCAGCTCGGCCCGCGCAAGCTGGACGCTGGGCAGACCCATGACCTTGCTGACGGTGCGCTCGATGTAATCCGCTTCGTGGCCGGGCTTGCGCTCTGCCAGCGCTGGGCTGGCCTCGGCCATGGCCTTGCCGATTTCCTCGGCACTGCGGCCCCGGCTGGCCAGCTTCTGCGCGGCGATAAAGTCGCACTTGCTGAGGTCATCACCGAAGCGCTTGACCAGCCCGGCCATCTCGCTGCGGTACTCGTCCAGCGCCGTGCGCCGGTGGCGGCTAAGCTGCCGCTCGGGCAGTTCGAGGCTGGCCAGCCTGCGGGCCTTCTCCTGCTGCCGCTGGGCCTGCTCGATCTGCTGGCCAGCCTGCTGCACCAGCGCCGGGCCAGCGGTGGCGGTCTTGCCCTTGGATTCACGCAGCAGCACCCACGGCTGATAACCGGCGCGGGTGGTGTGCTTGTCCTTGCGGTTGGTGAAGCCCGCCAAGCGGCCATAGTGGCGGCTGTCGGCGCTGGCCGGGTCGGCGTCGTACTCGCTGGCCAGCGTCCGGGCAATCTGCCCCCGAAGTTCACCGCCTGCGGCGTCGGCCACCTTGACCCATGCCTGATAGTTCTTCGGGCTGGTTTCCACTACCAGGGCAGGCTCCCGGCCCTCGGCTTTCATGTCATCCAGGTCAAACTCGCTGAGGTCGTCCACCAGCACCAGACCATGCCGCTCCTGCTCGGCGGGCCTGATATACACGTCATTGCCCTGGGCATTCATCCGCTTGAGCCATGGCGTGTTCTGGAGCACTTCGGCGGCTGACCATTCCCGGTTCATCATCTGGCCGGTGGTGGCGTCCCTGACGCCGATATCGAAGCGCTCACAGCCCATGGCCTTGAGCTGTCGGCCTATGGCCTGCAAAGTCCTGTCGTTCTTCATCGGGCCACCAAGCGATTCCCACACATTATACGAGCCGGAAGCATAAAGTGTAAAGCCTAGATCCGAAGGATGAGCCGGGCTGAATGATCGACCGAGACAGGCCCTGCGGGGCTGCACACGCGCCCCCACCCTTCGGGTAGGGGGAAAGGCCGCTAAAGCGGCTAAAAGCGCTCCAGCGTATTTCTGCGGGGTTTGGTGTGGGGTTTAGCGGGCTTTGCCCGCCTTTCCCCCTGCCGCGCAGCGGTGGGGCGGTGTGTAGCCTAGCGCAGCGAATAGACCAGCTATCCGGCCTCTGGCCGGGCATATTGGGCAAGGGCAGCAGCGCCCCACAAGGGCGCTGATAACCGCGCCTAGTGGATTATTCTTAGATAATCATGGATGGATTTTTCCAACACCCCGCCAGCCCCCGCCCCTGCTGGGTTTGCAGGTTTGGGGGCGTGACAGTTATTGCAGGGGTTCGTGACAGTTATTGCAGGGGGGCGTGACAGTTATTGCAGGGGTTCGTGACAGTTAGGGCGCGCCCAGCTGTCTAGGGCGGCGGATTTGTCCTACTCAGGAGAGCGTTCACCGACAAACAACAGATAAAACGAAAGGCCCAGTCTTTCGACTGAGCCTTTCGTTTTATTTGATGCCTGCTCTTCTATGACGGCATTGACGGAAGGCGCAAAATTGTTCGAAAAAGAAATCCCATACATCACCGAACTGGAAGGCGATGTTGAAGGTATGAAGTTCATCATTAAGGGTGAGGGCACCGGCGATGCAACTACGGGCACCATTAAAGCGAAGTATATCTGCACCACCGGTGACGTTCCGGTGCCGTGGAGCACGCTGGTCACCACCCTGACCTATGGCGCGCAGTGTTTCGCGAAGTACGGTCCGGAACTGAAGGACTTCTATAAGAGCTGTATGCCTGAGGGCTATGTTCAGGAGCGTACCATTACCTTTGAGGGTGATGGTGTCTTTAAGACGCGTGCTGAGGTGACCTTTGAGAATGGTTCCGTGTACAATCGCGTGAAACTGAATGGTCAAGGTTTTAAGAAAGATGGTCACGTGCTGGGCAAAAACCTGGAGTTTAACTTTACTCCGCATTGCCTGTGCATTTGGGGCGACCAAGCGAACCACGGTCTGAAAAGCGCGTTCAAGATTATGCACGAGATTACGGGTAGCAAAGAGGACTTCATCGTGGCCGACCACACGCAGATGAACACCCCGATCGGTGGCGGTCCGGTCCATGTCCCGGAGTACCACCACTTGACCGTTTGGACCTCTTTCGGTAAAGACCCGGATGATGACGAAACGGATCATCTGAATATTGTTGAGGTTATCAAAGCCGTCGACCTGGAAACTTACCGTTAATGATAATGA",
		Plasmid: true,
		},
	},
	{[]wtype.DNASequence{comet2part1, comet2part2},
		pSEVA651,
		SapI,
		wtype.DNASequence{
		Nm: "simulated assembly sequence", 
		Seq: "TTAATTAAAGCGGATAACAATTTCACACAGGAGGCCGCCTAGGCCGCGGCCGCGCGAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTTGCGGCCGCGTCGTGACTGGGAAAACCCTGGCGACTAGTCTTGGACTCCTGTTGATAGATCCAGTAATGACCTCAGAACTCCATCTGGATTTGTTCAGAACGCTCGGTTGCCGCCGGGCGTTTTTTATTGGTGAGAATCCAGGGGTCCCCAATAATTACGATTTAAATTTGACATAAGCCTGTTCGGTTCGTAAACTGTAATGCAAGTAGCGTATGCGCTCACGCAACTGGTCCAGAACCTTGACCGAACGCAGCGGTGGTAACGGCGCAGTGGCGGTTTTCATGGCTTGTTATGACTGTTTTTTTGTACAGCCTATGCCTCGGGCATCCAAGCAGCAAGCGCGTTACGCCGTGGGTCGATGTTTGATGTTATGGAGCAGCAACGATGTTACGCAGCAGCAACGATGTTACGCAGCAGGGCAGTCGCCCTAAAACAAAGTTAGGTGGCTCAAGTATGGGCATCATTCGCACATGTAGGCTCGGCCCTGACCAAGTCAAATCCATGCGGGCTGCTCTTGATCTTTTCGGTCGTGAGTTCGGAGACGTAGCCACCTACTCCCAACATCAGCCGGACTCCGATTACCTCGGGAACTTGCTCCGTAGTAAGACATTCATCGCGCTTGCTGCCTTCGACCAAGAAGCGGTTGTTGGCGCTCTCGCGGCTTACGTTCTGCCCAAGTTTGAGCAGCCGCGTAGTGAGATCTATATCTATGATCTCGCAGTCTCCGGAGAGCACCGGAGGCAGGGCATTGCCACCGCGCTCATCAATCTCCTCAAGCATGAGGCCAACGCGCTTGGTGCTTATGTGATCTACGTGCAAGCAGATTACGGTGACGATCCCGCAGTGGCTCTCTATACAAAGTTGGGCATACGGGAAGAAGTGATGCACTTTGATATCGACCCAAGTACCGCCACCTAACAATTCGTTCAAGCCGAGATCGGCTTCCCGGCCGCGGAGTTGTTCGGTAAATTGGACAACGGTCCGCGCGTTGTCCTTTTCCGCTGCATAACCCTGCTTCGGGGTCATTATAGCGATTTTTTCGGTATATCCATCCTTTTTCGCACGATATACAGGATTTTGCCAAAGGGTTCGTGTAGACTTTCCTTGGTGTATCCAACGGCGTCAGCCGGGCAGGATAGGTGAAGTAGGCCCACCCGCGAGCGGGTGTTCCTTCTTCACTGTCCCTTATTCGCACCTGGCGGTGCTCAACGGGAATCCTGCTCTGCGAGGCTGGCCGTAGGCCGGCCTCAGCCTGCCGCCTTGGGCCGGGTGATGTCGTACTTGCCCGCCGCGAACTCGGTTACCGTCCAGCCCAGCGCGACCAGCTCCGGCAACGCCTCGCGCACCCGCTGGCGGCGCTTGCGCATGGTCGAACCACTGGCCTCTGACGGCCAGACATAGCCGCACAAGGTATCTATGGAAGCCTTGCCGGTTTTGCCGGGGTCGATCCAGCCACACAGCCGCTGGTGCAGCAGGCGGGCGGTTTCGCTGTCCAGCGCCCGCACCTCGTCCATGCTGATGCGCACATGCTGGCCGCCACCCATGACGGCCTGCGCGATCAAGGGGTTCAGGGCCACGTACAGGCGCCCGTCCGCCTCGTCGCTGGCGTACTCCGACAGCAGCCGAAACCCCTGCCGCTTGCGGCCATTCTGGGCGATGATGGATACCTTCCAAAGGCGCTCGATGCAGTCCTGTATGTGCTTGAGCGCCCCACCACTATCGACCTCTGCCCCGATTTCCTTTGCCAGCGCCCGATAGCTACCTTTGACCACATGGCATTCAGCGGTGACGGCCTCCCACTTGGGTTCCAGGAACAGCCGGAGCTGCCGTCCGCCTTCGGTCTTGGGTTCCGGGCCAAGCACTAGGCCATTAGGCCCAGCCATGGCCACCAGCCCTTGCAGGATGCGCAGATCATCAGCGCCCAGCGGCTCCGGGCCGCTGAACTCGATCCGCTTGCCGTCGCCGTAGTCATACGTCACGTCCAGCTTGCTGCGCTTGCGCTCGCCCCGCTTGAGGGCACGGAACAGGCCGGGGGCCAGACAGTGCGCCGGGTCGTGCCGGACGTGGCTGAGGCTGTGCTTGTTCTTAGGCTTCACCACGGGGCACCCCCTTGCTCTTGCGCTGCCTCTCCAGCACGGCGGGCTTGAGCACCCCGCCGTCATGCCGCCTGAACCACCGATCAGCGAACGGTGCGCCATAGTTGGCCTTGCTCACACCGAAGCGGACGAAGAACCGGCGCTGGTCGTCGTCCACACCCCATTCCTCGGCCTCGGCGCTGGTCATGCTCGACAGGTAGGACTGCCAGCGGATGTTATCGACCAGTACCGAGCTGCCCCGGCTGGCCTGCTGCTGGTCGCCTGCGCCCATCATGGCCGCGCCCTTGCTGGCATGGTGCAGGAACACGATAGAGCACCCGGTATCGGCGGCGATGGCCTCCATGCGACCGATGACCTGGGCCATGGGGCCGCTGGCGTTTTCTTCCTCGATGTGGAACCGGCGCAGCGTGTCCAGCACCATCAGGCGGCGGCCCTCGGCGGCGCGCTTGAGGCCGTCGAACCACTCCGGGGCCATGATGTTGGGCAGGCTGCCGATCAGCGGCTGGATCAGCAGGCCGTCAGCCACGGCTTGCCGTTCCTCGGCGCTGAGGTGCGCCCCAAGGGCGTGCAGGCGGTGATGAATGGCGGTGGGCGGGTCTTCGGCGGGCAGGTAGATCACCGGGCCGGTGGGCAGTTCGCCCACCTCCAGCAGATCCGGCCCGCCTGCAATCTGTGCGGCCAGTTGCAGGGCCAGCATGGATTTACCGGCACCACCGGGCGACACCAGCGCCCCGACCGTACCGGCCACCATGTTGGGCAAAACGTAGTCCAGCGGTGGCGGCGCTGCTGCGAACGCCTCCAGAATATTGATAGGCTTATGGGTAGCCATTGATTGCCTCCTTTGCAGGCAGTTGGTGGTTAGGCGCTGGCGGGGTCACTACCCCCGCCCTGCGCCGCTCTGAGTTCTTCCAGGCACTCGCGCAGCGCCTCGTATTCGTCGTCGGTCAGCCAGAACTTGCGCTGACGCATCCCTTTGGCCTTCATGCGCTCGGCATATCGCGCTTGGCGTACAGCGTCAGGGCTGGCCAGCAGGTCGCCGGTCTGCTTGTCCTTTTGGTCTTTCATATCAGTCACCGAGAAACTTGCCGGGGCCGAAAGGCTTGTCTTCGCGGAACAAGGACAAGGTGCAGCCGTCAAGGTTAAGGCTGGCCATATCAGCGACTGAAAAGCGGCCAGCCTCGGCCTTGTTTGACGTATAACCAAAGCCACCGGGCAACCAATAGCCCTTGTCACTTTTGATCAGGTAGACCGACCCTGAAGCGCTTTTTTCGTATTCCATAAAACCCCCTTCTGTGCGTGAGTACTCATAGTATAACAGGCGTGAGTACCAACGCAAGCACTACATGCTGAAATCTGGCCCGCCCCTGTCCATGCCTCGCTGGCGGGGTGCCGGTGCCCGTGCCAGCTCGGCCCGCGCAAGCTGGACGCTGGGCAGACCCATGACCTTGCTGACGGTGCGCTCGATGTAATCCGCTTCGTGGCCGGGCTTGCGCTCTGCCAGCGCTGGGCTGGCCTCGGCCATGGCCTTGCCGATTTCCTCGGCACTGCGGCCCCGGCTGGCCAGCTTCTGCGCGGCGATAAAGTCGCACTTGCTGAGGTCATCACCGAAGCGCTTGACCAGCCCGGCCATCTCGCTGCGGTACTCGTCCAGCGCCGTGCGCCGGTGGCGGCTAAGCTGCCGCTCGGGCAGTTCGAGGCTGGCCAGCCTGCGGGCCTTCTCCTGCTGCCGCTGGGCCTGCTCGATCTGCTGGCCAGCCTGCTGCACCAGCGCCGGGCCAGCGGTGGCGGTCTTGCCCTTGGATTCACGCAGCAGCACCCACGGCTGATAACCGGCGCGGGTGGTGTGCTTGTCCTTGCGGTTGGTGAAGCCCGCCAAGCGGCCATAGTGGCGGCTGTCGGCGCTGGCCGGGTCGGCGTCGTACTCGCTGGCCAGCGTCCGGGCAATCTGCCCCCGAAGTTCACCGCCTGCGGCGTCGGCCACCTTGACCCATGCCTGATAGTTCTTCGGGCTGGTTTCCACTACCAGGGCAGGCTCCCGGCCCTCGGCTTTCATGTCATCCAGGTCAAACTCGCTGAGGTCGTCCACCAGCACCAGACCATGCCGCTCCTGCTCGGCGGGCCTGATATACACGTCATTGCCCTGGGCATTCATCCGCTTGAGCCATGGCGTGTTCTGGAGCACTTCGGCGGCTGACCATTCCCGGTTCATCATCTGGCCGGTGGTGGCGTCCCTGACGCCGATATCGAAGCGCTCACAGCCCATGGCCTTGAGCTGTCGGCCTATGGCCTGCAAAGTCCTGTCGTTCTTCATCGGGCCACCAAGCGATTCCCACACATTATACGAGCCGGAAGCATAAAGTGTAAAGCCTAGATCCGAAGGATGAGCCGGGCTGAATGATCGACCGAGACAGGCCCTGCGGGGCTGCACACGCGCCCCCACCCTTCGGGTAGGGGGAAAGGCCGCTAAAGCGGCTAAAAGCGCTCCAGCGTATTTCTGCGGGGTTTGGTGTGGGGTTTAGCGGGCTTTGCCCGCCTTTCCCCCTGCCGCGCAGCGGTGGGGCGGTGTGTAGCCTAGCGCAGCGAATAGACCAGCTATCCGGCCTCTGGCCGGGCATATTGGGCAAGGGCAGCAGCGCCCCACAAGGGCGCTGATAACCGCGCCTAGTGGATTATTCTTAGATAATCATGGATGGATTTTTCCAACACCCCGCCAGCCCCCGCCCCTGCTGGGTTTGCAGGTTTGGGGGCGTGACAGTTATTGCAGGGGTTCGTGACAGTTATTGCAGGGGGGCGTGACAGTTATTGCAGGGGTTCGTGACAGTTAGGGCGCGCCCAGCTGTCTAGGGCGGCGGATTTGTCCTACTCAGGAGAGCGTTCACCGACAAACAACAGATAAAACGAAAGGCCCAGTCTTTCGACTGAGCCTTTCGTTTTATTTGATGCCTGCTCTTCTATGACGGCATTGACGGAAGGCGCAAAATTGTTCGAAAAAGAAATCCCATACATCACCGAACTGGAAGGCGATGTTGAAGGTATGAAGTTCATCATTAAGGGTGAGGGCACCGGCGATGCAACTACGGGCACCATTAAAGCGAAGTATATCTGCACCACCGGTGACGTTCCGGTGCCGTGGAGCACGCTGGTCACCACCCTGACCTATGGCGCGCAGTGTTTCGCGAAGTACGGTCCGGAACTGAAGGACTTCTATAAGAGCTGTATGCCTGAGGGCTATGTTCAGGAGCGTACCATTACCTTTGAGGGTGATGGTGTCTTTAAGACGCGTGCTGAGGTGACCTTTGAGAATGGTTCCGTGTACAATCGCGTGAAACTGAATGGTCAAGGTTTTAAGAAAGATGGTCACGTGCTGGGCAAAAACCTGGAGTTTAACTTTACTCCGCATTGCCTGTGCATTTGGGGCGACCAAGCGAACCACGGTCTGAAAAGCGCGTTCAAGATTATGCACGAGATTACGGGTAGCAAAGAGGACTTCATCGTGGCCGACCACACGCAGATGAACACCCCGATCGGTGGCGGTCCGGTCCATGTCCCGGAGTACCACCACTTGACCGTTTGGACCTCTTTCGGTAAAGACCCGGATGATGACGAAACGGATCATCTGAATATTGTTGAGGTTATCAAAGCCGTCGACCTGGAAACTTACCGTTAATGATAATGA",
		Plasmid: true,
		},
	},
}

func TestJointwopartsfromsequence(t *testing.T) {
	desiredproductisamongpossibilities := false
	for _, assembly := range assemblytests {
		_, plasmidProducts := Jointwopartsfromsequence(assembly.vector, assembly.parts[0], assembly.enzyme)
		for i := 0; i < len(plasmidProducts)-1; i++ {
			if !reflect.DeepEqual(plasmidProducts[i],assembly.desiredassemblyproduct) {
				desiredproductisamongpossibilities = true
			}
			if desiredproductisamongpossibilities != true {
				t.Error(
					"For", assembly, "\n",
					"expected", assembly.desiredassemblyproduct, "\n",
					"got", plasmidProducts[0], "\n",
					"got", plasmidProducts[1], "\n",
				)

			}
		}
	}

}

func TestJoinXnumberofparts(t *testing.T) {
	desiredproductisamongpossibilities := false
	for _, assembly := range assemblytests {
		_, plasmidProducts,_,_ := JoinXNumberOfParts(assembly.vector, assembly.parts, assembly.enzyme)

		for i := 0; i < len(plasmidProducts)-1; i++ {
			if !reflect.DeepEqual(plasmidProducts[i], assembly.desiredassemblyproduct) {
				desiredproductisamongpossibilities = true
			}
			if desiredproductisamongpossibilities != true {
				t.Error(
					"For", assembly, "\n",
					"expected", assembly.desiredassemblyproduct, "\n",
					"got", plasmidProducts[0], "\n",
					"got", plasmidProducts[1], "\n",
				)

			}
		}
	}

}
