package compile

import (
	"bytes"
	"io"
	"io/ioutil"
)

// An AnthaFile is a file generated by the Antha translation process
type AnthaFile struct {
	// Name is a slash-delimited filename
	Name string
	Data *bytes.Buffer
}

// NewReader returns a new reader for this file
func (f *AnthaFile) NewReader() io.ReadCloser {
	return ioutil.NopCloser(f.Data)
}

// AnthaFiles is a collection of AnthaFiles
type AnthaFiles struct {
	files []*AnthaFile
}

// NewAnthaFiles returns a new collection of AnthaFiles
func NewAnthaFiles() *AnthaFiles {
	return &AnthaFiles{}
}

// Files returns the files in the collection
func (f *AnthaFiles) Files() []*AnthaFile {
	return f.files
}

func (f *AnthaFiles) addFile(name string, data *bytes.Buffer) {
	f.files = append(f.files, &AnthaFile{
		Name: name,
		Data: data,
	})
}
