package composer

import (
	"fmt"
	"io"
	"path"
	"strings"
	"text/template"
	"unicode"
)

type mainRenderer struct {
	*Composer
	varCount uint64
	varMemo  map[string]string
}

func (mr *mainRenderer) render(w io.Writer) error {
	funcs := template.FuncMap{
		"varName":        mr.varName,
		"elementClasses": mr.elementClasses,
		"packageName":    packageName,
	}
	if t, err := template.New("main").Funcs(funcs).Parse(tpl); err != nil {
		return err
	} else {
		return t.Execute(w, mr.Workflow)
	}
}

func (mr *mainRenderer) varName(name string) string {
	if res, found := mr.varMemo[name]; found {
		return res
	}

	res := make([]rune, 0, len(name))
	ensureUpper := false
	for _, r := range []rune(name) {
		switch {
		case 'a' <= r && r <= 'z' && ensureUpper:
			ensureUpper = false
			res = append(res, unicode.ToUpper(r))
		case 'a' <= r && r <= 'z':
			res = append(res, r)
		case 'A' <= r && r <= 'Z' && len(res) == 0:
			res = append(res, unicode.ToLower(r))
		case 'A' <= r && r <= 'Z':
			res = append(res, r)
			ensureUpper = false
		case strings.ContainsRune(" -_", r):
			ensureUpper = true
		}
	}
	resStr := fmt.Sprintf("%s%d", string(res), mr.varCount)
	mr.varCount++
	mr.varMemo[name] = resStr
	return resStr
}

func (mr *mainRenderer) elementClasses() map[string]*LocatedElement {
	return mr.classes
}

func packageName(element string) string {
	return path.Base(element)
}

var tpl = `// Code generated by antha composer. DO NOT EDIT.
package main

import (
	"github.com/antha-lang/antha/laboratory"

{{range elementClasses}}	{{printf "%q" .ImportPath}}
{{end}})

func main() {
	labBuild := laboratory.NewLaboratoryBuilder({{printf "%q" .JobId}})
	// Register line maps for the elements we're using
{{range elementClasses}}	{{.PackageName}}.RegisterLineMap(labBuild)
{{end}}
	// Create the elements
{{range $name, $proc := .Processes}}	{{varName $name}} := {{packageName $proc.Component}}.New(labBuild, {{printf "%q" $name}})
{{end}}
	// Add wiring
{{range .Connections}}	labBuild.AddLink({{varName .Source.Process}}, {{varName .Target.Process}}, func () { {{varName .Target.Process}}.Inputs.{{.Target.Port}} = {{varName .Source.Process}}.Outputs.{{.Source.Port}} })
{{end}}
	// Set parameters
{{range $name, $params := .Parameters}}{{range $param, $value := $params}}	if err := {{varName $name}}.Inputs.{{$param}}.SetFromJSON([]byte({{printf "%q" $value}})); err != nil {
		labBuild.Fatal(err)
	}
{{end}}{{end}}
	// Run!
	if err := labBuild.Run(); err != nil {
		labBuild.Fatal(err)
	}
}
`
