// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/antha-lang/antha/driver/antha_framework_v1/framework.proto

/*
Package antha_framework_v1 is a generated protocol buffer package.

It is generated from these files:
	github.com/antha-lang/antha/driver/antha_framework_v1/framework.proto

It has these top-level messages:
	CommandDescription
	CommandData
	CommandMetadata
	CommandRequest
	CommandResponse
	BatchedCommandRequest
	BatchedCommandResponse
*/
package antha_framework_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommandDescription struct {
	CommandName string `protobuf:"bytes,1,opt,name=command_name,json=commandName" json:"command_name,omitempty"`
	DeviceId    string `protobuf:"bytes,2,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	CommandId   string `protobuf:"bytes,3,opt,name=command_id,json=commandId" json:"command_id,omitempty"`
}

func (m *CommandDescription) Reset()                    { *m = CommandDescription{} }
func (m *CommandDescription) String() string            { return proto.CompactTextString(m) }
func (*CommandDescription) ProtoMessage()               {}
func (*CommandDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommandDescription) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *CommandDescription) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *CommandDescription) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

type CommandData struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CommandData) Reset()                    { *m = CommandData{} }
func (m *CommandData) String() string            { return proto.CompactTextString(m) }
func (*CommandData) ProtoMessage()               {}
func (*CommandData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommandMetadata struct {
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId" json:"job_id,omitempty"`
}

func (m *CommandMetadata) Reset()                    { *m = CommandMetadata{} }
func (m *CommandMetadata) String() string            { return proto.CompactTextString(m) }
func (*CommandMetadata) ProtoMessage()               {}
func (*CommandMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CommandMetadata) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type CommandRequest struct {
	Description *CommandDescription `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Data        *CommandData        `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Metadata    *CommandMetadata    `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *CommandRequest) Reset()                    { *m = CommandRequest{} }
func (m *CommandRequest) String() string            { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()               {}
func (*CommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CommandRequest) GetDescription() *CommandDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *CommandRequest) GetData() *CommandData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CommandRequest) GetMetadata() *CommandMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CommandResponse struct {
	Request  *CommandRequest `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response *CommandData    `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *CommandResponse) Reset()                    { *m = CommandResponse{} }
func (m *CommandResponse) String() string            { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()               {}
func (*CommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CommandResponse) GetRequest() *CommandRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *CommandResponse) GetResponse() *CommandData {
	if m != nil {
		return m.Response
	}
	return nil
}

type BatchedCommandRequest struct {
	Request []*CommandRequest `protobuf:"bytes,1,rep,name=request" json:"request,omitempty"`
}

func (m *BatchedCommandRequest) Reset()                    { *m = BatchedCommandRequest{} }
func (m *BatchedCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchedCommandRequest) ProtoMessage()               {}
func (*BatchedCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BatchedCommandRequest) GetRequest() []*CommandRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type BatchedCommandResponse struct {
	Response []*CommandResponse `protobuf:"bytes,1,rep,name=response" json:"response,omitempty"`
}

func (m *BatchedCommandResponse) Reset()                    { *m = BatchedCommandResponse{} }
func (m *BatchedCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*BatchedCommandResponse) ProtoMessage()               {}
func (*BatchedCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BatchedCommandResponse) GetResponse() []*CommandResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*CommandDescription)(nil), "antha.framework.v1.CommandDescription")
	proto.RegisterType((*CommandData)(nil), "antha.framework.v1.CommandData")
	proto.RegisterType((*CommandMetadata)(nil), "antha.framework.v1.CommandMetadata")
	proto.RegisterType((*CommandRequest)(nil), "antha.framework.v1.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "antha.framework.v1.CommandResponse")
	proto.RegisterType((*BatchedCommandRequest)(nil), "antha.framework.v1.BatchedCommandRequest")
	proto.RegisterType((*BatchedCommandResponse)(nil), "antha.framework.v1.BatchedCommandResponse")
}

func init() {
	proto.RegisterFile("github.com/antha-lang/antha/driver/antha_framework_v1/framework.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x5f, 0x6b, 0xea, 0x30,
	0x18, 0xc6, 0xa9, 0x9e, 0xe3, 0xd1, 0xb7, 0x72, 0x0e, 0x04, 0x3c, 0x08, 0x87, 0xc3, 0x66, 0x84,
	0xe1, 0xcd, 0x2a, 0xea, 0xe5, 0x06, 0xc2, 0xfe, 0xc0, 0xbc, 0xd8, 0x2e, 0x0a, 0xbb, 0xd8, 0x55,
	0x79, 0xdb, 0x64, 0x5a, 0xb7, 0x36, 0x2e, 0x8d, 0xdd, 0x97, 0xd8, 0x87, 0xdb, 0x47, 0x1a, 0x26,
	0x69, 0x75, 0x0a, 0x65, 0xbb, 0x4b, 0x9e, 0xbc, 0xcf, 0x93, 0xe7, 0x17, 0x02, 0xd7, 0xf3, 0x58,
	0x2d, 0xd6, 0xa1, 0x17, 0x89, 0x64, 0x88, 0xa9, 0x5a, 0xe0, 0xe9, 0x33, 0xa6, 0x73, 0xb3, 0x1c,
	0x32, 0x19, 0xe7, 0x5c, 0x9a, 0x4d, 0xf0, 0x28, 0x31, 0xe1, 0xaf, 0x42, 0x3e, 0x05, 0xf9, 0x68,
	0x58, 0x6e, 0xbc, 0x95, 0x14, 0x4a, 0x10, 0xa2, 0x67, 0xbc, 0xad, 0x9c, 0x8f, 0x68, 0x06, 0xe4,
	0x52, 0x24, 0x09, 0xa6, 0xec, 0x8a, 0x67, 0x91, 0x8c, 0x57, 0x2a, 0x16, 0x29, 0xe9, 0x41, 0x3b,
	0x32, 0x6a, 0x90, 0x62, 0xc2, 0xbb, 0xce, 0xb1, 0x33, 0x68, 0xf9, 0xae, 0xd5, 0xee, 0x30, 0xe1,
	0xe4, 0x1f, 0xb4, 0x18, 0xcf, 0xe3, 0x88, 0x07, 0x31, 0xeb, 0xd6, 0xf4, 0x79, 0xd3, 0x08, 0x33,
	0x46, 0xfe, 0x03, 0x14, 0xfe, 0x98, 0x75, 0xeb, 0xfa, 0xb4, 0x65, 0x95, 0x19, 0xa3, 0x3d, 0x70,
	0x8b, 0x4b, 0x51, 0x21, 0x21, 0xf0, 0x83, 0xa1, 0x42, 0x7d, 0x4b, 0xdb, 0xd7, 0x6b, 0x3a, 0x80,
	0x3f, 0x76, 0xe4, 0x96, 0x2b, 0xdc, 0x48, 0xa4, 0x03, 0x8d, 0xa5, 0x08, 0x37, 0x81, 0xa6, 0xce,
	0xcf, 0xa5, 0x08, 0x67, 0x8c, 0xbe, 0x3b, 0xf0, 0xdb, 0x8e, 0xfa, 0xfc, 0x65, 0xcd, 0x33, 0x45,
	0x6e, 0xc0, 0x65, 0x5b, 0x1a, 0x3d, 0xee, 0x8e, 0x4f, 0xbc, 0x43, 0x7c, 0xef, 0x90, 0xdd, 0xdf,
	0xb5, 0x92, 0x89, 0xad, 0x56, 0xd3, 0x11, 0x47, 0x55, 0x11, 0xa8, 0xd0, 0x74, 0x27, 0x53, 0x68,
	0x26, 0xb6, 0xb4, 0x66, 0x77, 0xc7, 0xfd, 0x0a, 0x63, 0xc1, 0xe7, 0x97, 0x26, 0xfa, 0xe6, 0x94,
	0xf4, 0x3e, 0xcf, 0x56, 0x22, 0xcd, 0x38, 0x39, 0x87, 0x5f, 0xd2, 0xe0, 0x59, 0x1e, 0x5a, 0x91,
	0x69, 0x1f, 0xc2, 0x2f, 0x2c, 0xe4, 0x0c, 0x9a, 0xd2, 0x26, 0x7d, 0x95, 0xa5, 0x34, 0xd0, 0x7b,
	0xe8, 0x5c, 0xa0, 0x8a, 0x16, 0x9c, 0xed, 0xbd, 0xf3, 0xa7, 0x4e, 0xf5, 0x6f, 0x76, 0xa2, 0x0f,
	0xf0, 0x77, 0x3f, 0xd6, 0xb2, 0x4e, 0x77, 0xda, 0x9a, 0xe0, 0x7e, 0x65, 0xb0, 0x19, 0xdd, 0x36,
	0x0e, 0x1b, 0xfa, 0xc3, 0x4f, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x10, 0xb1, 0x4d, 0x7c, 0x39,
	0x03, 0x00, 0x00,
}
